### ISSUE TITLE
submit reference in manual capture call

### ISSUE THREAD

**Issue by jvoges** [commercetools/commercetools-adyen-integration#1003]
when looking at the code, it doesn't seem to be possible to add a reference to the manual capture request (which would translate to modification reference).

-> https://github.com/commercetools/commercetools-adyen-integration/blob/06e36997847f1d962e64520e79e118a98dd950b4/extension/src/paymentHandler/manual-capture.handler.js

this would be really handy for us, to use the commercetools `orderNumber` for this, so that mapping between order and payment would be much easier (in the browser and in exports used for matching payments in erp).

using any fields in `makePaymentRequest` is not an option, as the order does not yet exist.

have i overlooked anything? if not, would it be a feature that can be implemented?

**Comment by lojzatran** [comment]
Hi @jvoges 

Thank you for contacting us.

I checked and indeed there is no `reference` field for manual capture request. I will create an internal JIRA ticket for this issue so that we can address it.

I will let you know once we start working on the issue.

**Comment by butenkor** [comment]
Issue fixed and released: https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v9.12.0
