### ISSUE TITLE
Authorization Cancellation

### ISSUE THREAD

**Issue by LSshopmacher** [commercetools/commercetools-adyen-integration#1032]
I wrote with Adyen about the Cancellation call you describe here https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/CancelPayment.md

from your doc:
> The amount field in the transaction is ignored. Adyen doesn't require the amount to be provided as cancellation could be done only for the whole amount.

We use 9999€ as generic amount because we want to cancel the remaining amount. The Adyen support wrote:

> To avoid technical issues do not include "amount: 999900" or anything similar in the cancellation call. Only perform the /cancel request when you are certain that you completed all the necessary (partial) captures on an authorized amount.

I guess you should remove this amount field completly in the extension?

**Comment by lojzatran** [comment]
Hi @LSshopmacher 

Thank you for the suggestion.

As you can [see we do not include amount in our code and do not send it to Adyen](https://github.com/commercetools/commercetools-adyen-integration/blob/f538a24a605938556ffc843075419fdc8d4a3218/extension/src/paymentHandler/cancel-payment.handler.js#L18). However, `amount` field is required when adding a [new transaction in commercetools](https://docs.commercetools.com/api/projects/payments#transactiondraft). Thus this field is documented in the example.
