### ISSUE TITLE
Adyen web components >= v5.0.0 integration

### ISSUE THREAD

**Issue by GerardoVentura** [commercetools/commercetools-adyen-integration#1033]
Hello. I'm currently developing an integration of this plug-in on the FE side. I'm using  [Web Components v5.28.0](https://docs.adyen.com/online-payments/release-notes?tab=v5-0-0-or-later_2021-10-04-stzc_1#releaseNote=2022-10-10-web-componentsdrop-in-5.28.0) and according to the [Adyen's official documentation](https://docs.adyen.com/online-payments/web-components) for the web component after the version 5.0.0, they no longer offer a parameter to define the `onSubmit` method/logic inside the component configuration object , instead Adyen offers another method called `onPaymentCompleted(result, component)` which is called once the transaction is being done (internally calls the endpoint /payments to their API)

Being that said, I'm wondering if there's an alternative we can use for version 5.0.0 and later in order to catch Adyen encrypted data to then include it into the payload sent to the Commerce Tools extension/plugin.

**Comment by lojzatran** [comment]
Hi @GerardoVentura,

Thank you for the request.

We do not currently support Web Components version 5+. As you wrote above there is no way to send the payload to the extension module (see also here: https://github.com/commercetools/commercetools-adyen-integration/blob/master/docs/FAQ.md#can-i-use-adyen-web-components--v500-with-this-integration-)

However, we got this information from Adyen support a while ago and the situation might have changed. So you can try to clarify this question with Adyen support: https://www.adyen.help/hc/en-us/requests/new

**Comment by GerardoVentura** [comment]
Hi @lojzatran,

Thanks for the explanation. I'll be in touch with the Adyen support to clarify my question.
