### ISSUE TITLE
Question about retry policy for submitAdditionalPaymentDetailsRequest

### ISSUE THREAD

**Issue by BielsasBucket** [commercetools/commercetools-adyen-integration#1046]
Hi,

We were wondering, if we were to submit our Update Payment action again for `submitAdditionalPaymentDetailsRequest` whether this would call Adyen again resulting in duplicated payments, if a transaction was present?

We are asking, as we are encountering errors where the **transaction** and **interface interaction** updates are added to a payment before the `submitAdditionalPaymentDetailsRequest` and `submitAdditionalPaymentDetailsResponse` can be added to the payment resulting in a `ConcurrentModificationException`.

Hope this is clear,

Thanks

**Comment by BielsasBucket** [comment]
I think the answer is yes, as looking at the code, it would attempt to CallAdyen again and that might throw an error?

**Comment by butenkor** [comment]
Hi @BielsasBucket,

> We were wondering, if we were to submit our Update Payment action again for submitAdditionalPaymentDetailsRequest whether this would call Adyen again resulting in duplicated payments, if a transaction was present?

We would process it if there is no [submitAdditionalPaymentDetailsResponse](submitAdditionalPaymentDetailsRequest) yet or new request [differs](https://github.com/commercetools/commercetools-adyen-integration/blob/04e374968639fa195a7d776439dec1331aa09e31/extension/src/paymentHandler/submit-payment-details.handler.js#L62) from the previous one.

> We are asking, as we are encountering errors where the transaction and interface interaction updates are added to a payment before the submitAdditionalPaymentDetailsRequest and submitAdditionalPaymentDetailsResponse can be added to the payment resulting in a ConcurrentModificationException

This might happen if asynchronous notification from Adyen reached the notification module before you supplied submitAdditionalPaymentDetailsRequest. In such case, depending on the notification a transaction might be already created in commercetools with the state `Pending` and than on your submitAdditionalPaymentDetailsRequest it would change its state to `Success`. ConcurrentModificationException might always happen when you work with commercetools API and you should be prepared for such situations by re-fetch, re-calculate of the update actions and update retry (if necessary). For more details please see [here](https://docs.commercetools.com/api/errors#concurrentmodification).

**Comment by BielsasBucket** [comment]
Thanks @butenkor - will take a look.
