### ISSUE TITLE
Getting Error while running

### ISSUE THREAD

**Issue by Meghana-aspire** [commercetools/commercetools-adyen-integration#1057]
Hi,
while running npm run test command in extension module I am getting error.Please suggest me on this.
![payment](https://user-images.githubusercontent.com/107937315/212068935-7a2dd2ac-0b0a-4be9-8fea-728e6e3d7ba7.png)

**Comment by Meghana-aspire** [comment]
Hi @praveenkumarct 
Thanks for the response,
I already created external file for environment variable in the form of .extensionrc file after that, is there any need of this command 
export ADYEN_INTEGRATION_CONFIG=xxxx
npm run setup-resources
means after exporting ADYEN_INTEGRATION_CONFIG environment variable only am I able to run the tests. I didn't run this command before and currently I don't have apiExtensionBaseUrl too.

**Comment by praveenkumarct** [comment]
Hello @Meghana-aspire,

 Thank you for the details. 
 Yes, seems like these unit tests needs to be fixed for your case.
 I will fix these tests on config in the next few days.
 
 Other than `config.spec.js` test failures, do you see any other issues?
