### ISSUE TITLE
Does the integration support tokenization?

### ISSUE THREAD

**Issue by BielsasBucket** [commercetools/commercetools-adyen-integration#1063]
Hello,

We were wondering if this integration supports tokenization as described here: https://docs.adyen.com/online-payments/tokenization/create-and-use-tokens#page-introduction

When trying this, we do not see the additional data returned in the Payment Response. We have enabled it in Adyen as per the guide written [see above]

Thanks

**Request:**

`{"channel":"Web","recurringProcessingModel":"CardOnFile","shopperInteraction":"Ecommerce","additionalData":{"allow3DS2":"true"},"amount":{"currency":"GBP","value":0},"applicationInfo":{"merchantApplication":{"name":"commercetools-adyen-integration-extension","version":"9.9.1"},"externalPlatform":{"name":"commercetools","integrator":"commercetools Professional Services"}},"billingAddress":{"city":"London","country":"GB","houseNumberOrName":"221 B","postalCode":"NW1 6XE","street":"Baker Street"},"deliveryAddress":{"city":"London","country":"GB","houseNumberOrName":"221 B","postalCode":"NW1 6XE","street":"Baker Street"},"lineItems":[{"amountIncludingTax":400,"description":"Trainers","id":"Item 1","quantity":1}],"merchantAccount":"S0016_FA_Web","metadata":{"orderNumber":"TestExample1234567890","ctProjectKey":"fa-compcomm-dev"},"paymentMethod":{"type":"scheme","encryptedCardNumber":"test_4444333322221111","encryptedExpiryMonth":"test_03","encryptedExpiryYear":"test_2030","encryptedSecurityCode":"test_737","holderName":"Sherlock Holmes"},"origin":"https://your-company.com","reference":"303a2fc2-c6e0-45aa-b22d-1ba224716e60","returnUrl":"https://your-company.com/api/handleShopperRedirect?paymentId=303a2fc2-c6e0-45aa-b22d-1ba224716e60","shopperEmail":"sherlock.holmes@famouspeople.com","shopperIP":"::1","shopperName":{"firstName":"Sherlock","lastName":"Holmes"},"shopperReference":"TestExample1234567890","storePaymentMethod":true,"telephoneNumber":"+44 20 7224 3688"}`

**Response:**

`{"pspReference":"QV5WFMH27DQ2WN82","resultCode":"Authorised","amount":{"currency":"GBP","value":0},"merchantReference":"303a2fc2-c6e0-45aa-b22d-1ba224716e60"}`

**Comment by BielsasBucket** [comment]
I have also raised this with Adyen, to make sure I have not missed something with the setup. I note that the payment in Adyen seems to have all the recurring information but I just don't get it back.

**Comment by leungkinghin** [comment]
@BielsasBucket Thank you for your reporting.
Indeed we don't have any extra implementation to rule out recurring payment.  We only transfer what you have given to /payment endpoint. I suppose the request is obtained from `custom.fields.makePaymentRequest`. As long as you have provided `recurringProcessingModel` and other necessary attributes for recurring payment in makePayment request,
it should successfully create the recurring payment in Adyen side.

In case you have already raised a ticket to Adyen, you can check with their team and ask them to investigate why the expected response doesn't contain `additionalData`

**Comment by leungkinghin** [comment]
I have checked the following document
https://docs.adyen.com/online-payments/tokenization/create-and-use-tokens?tab=one_off_payments_1#save-for-one-off

and i saw the required attributes seem to be given already within your request. But I would suggest you to ask Adyen technical team to verify your requests.

**Comment by BielsasBucket** [comment]
Hi,

Spoken with Adyen, who say they return the following response in their backend:

`{   "additionalData" : {      "recurringProcessingModel" : "CardOnFile",      "recurring.shopperReference" : "T011***********8787878",      "recurring.recurringDetailReference" : "S5K84T69N6KXWD82"   },   "pspReference" : "P9D55X558DQ2WN82",   "resultCode" : "Authorised",   "amount" : {      "currency" : "GBP",      "value" : 0   },   "merchantReference" : "8fb2da48-36c6-4c3f-9e49-b94deec55849"}`

 I do not see this returned in Make Payment Response, here are the full request, response from commercetools payment:

"makePaymentRequest": **"{\"channel\":\"Web\",\"recurringProcessingModel\":\"CardOnFile\",\"shopperInteraction\":\"Ecommerce\",\"additionalData\":{\"allow3DS2\":\"true\"},\"amount\":{\"currency\":\"GBP\",\"value\":0},\"applicationInfo\":{\"adyenLibrary\":{\"name\":\"adyen-dotnet-api-library\",\"version\":\"9.2.0\"}},\"billingAddress\":{\"city\":\"London\",\"country\":\"GB\",\"houseNumberOrName\":\"221 B\",\"postalCode\":\"NW1 6XE\",\"street\":\"Baker Street\"},\"deliveryAddress\":{\"city\":\"London\",\"country\":\"GB\",\"houseNumberOrName\":\"221 B\",\"postalCode\":\"NW1 6XE\",\"street\":\"Baker Street\"},\"lineItems\":[{\"amountIncludingTax\":400,\"description\":\"Trainers\",\"id\":\"Item 1\",\"quantity\":1}],\"merchantAccount\":\"S0016_FA_Web\",\"metadata\":{\"orderNumber\":\"T011521999787878787878\"},\"paymentMethod\":{\"type\":\"scheme\",\"encryptedCardNumber\":\"test_4444333322221111\",\"encryptedExpiryMonth\":\"test_03\",\"encryptedExpiryYear\":\"test_2030\",\"encryptedSecurityCode\":\"test_737\",\"holderName\":\"Sherlock Holmes\"},\"origin\":\"https://your-company.com\",\"reference\":\"8fb2da48-36c6-4c3f-9e49-b94deec55849\",\"returnUrl\":\"https://your-company.com/api/handleShopperRedirect?paymentId=8fb2da48-36c6-4c3f-9e49-b94deec55849\",\"shopperEmail\":\"sherlock.holmes@famouspeople.com\",\"shopperIP\":\"::1\",\"shopperName\":{\"firstName\":\"Sherlock\",\"lastName\":\"Holmes\"},\"shopperReference\":\"T011521999787878787878\",\"storePaymentMethod\":true,\"telephoneNumber\":\"+44 20 7224 3688\"}"**

"makePaymentResponse": **"{\"pspReference\":\"P9D55X558DQ2WN82\",\"resultCode\":\"Authorised\",\"amount\":{\"currency\":\"GBP\",\"value\":0},\"merchantReference\":\"8fb2da48-36c6-4c3f-9e49-b94deec55849\"}"**

Can someone please look at this?I do believe there is an issue here with not returning the data.

**Comment by BielsasBucket** [comment]
extension/src/service/web-component-service.js

Lines 219 - 221 might be the problem:

```
// strip away sensitive data from the adyen response.
    request.headers['X-Api-Key'] = '***'
    if (removeSensitiveData && responseBody) {
      delete responseBody.additionalData
    }
```

**Comment by BielsasBucket** [comment]
I just need to set the config as required.
