### ISSUE TITLE
order and payment creation order

### ISSUE THREAD

**Issue by jakinluk** [commercetools/commercetools-adyen-integration#1068]
The documentation provided here suggests order creation should be performed after payment is complete. 
https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/WebComponentsIntegrationGuide.md#web-components-integration-guide 
Is there any particular reason you suggest that flow?

The common and I believe best practice is to create an order first and then update its status after the payment is complete.

**Comment by leungkinghin** [comment]
@jakinluk This practice makes sure that order is created only payment is successfully authorized by Payment company. Otherwise we need to update/cancel the order after payment is authorized/rejected, which means extra traffic over the network is required.

Can you raise out any use case which requires order creation beforehand?

**Comment by jakinluk** [comment]
@leungkinghin there are many reasons for the order to be created as a first thing. 

We know the payment process is in its nature an asynchronous thing, right?  

Consider following scenarios 
- the payment gateway had a delay in the payment processing, 
- there was an issue on the webhook side, and there was an error while handling notification about payment completion and the order couldn't be created.
In those scenarios, the customer is left alone confused, without an error message, without an order, and still with a non-empty cart.

But if we place an order first, the customer will find that order in the orders tab, the order with the status 'awaiting payment'.

According to:

> Otherwise we need to update/cancel the order after payment is authorized/rejected, which means extra traffic over the network is required.
Updating, canceling, or changing the state of the order is something natural for the Order model in the context of an e-commerce subdomain. Extra traffic over the network is not an argument at all.

I would reference that discussion here as well https://softwareengineering.stackexchange.com/questions/319658/do-you-create-an-order-before-or-after-payment-on-an-ecommerce-site

**Comment by butenkor** [comment]
Hi @jakinluk, please check the FAQ section [here](https://github.com/commercetools/commercetools-adyen-integration/blob/master/docs/FAQ.md#when-i-should-create-commercetools-order-) since it should address your question.

**Comment by jakinluk** [comment]
@butenkor thanks. I went over it. 
I won't make you change your mind but the possible issues for https://github.com/commercetools/commercetools-adyen-integration/blob/master/docs/FAQ.md#what-to-consider-when-creating-an-order-after-a-successful-commercetools-payment- are far way more critical than those listed here: https://github.com/commercetools/commercetools-adyen-integration/blob/master/docs/FAQ.md#what-to-consider-when-creating-an-order-before-a-successful-commercetools-payment-, which are honestly stretched arguments. 

> If the shopper never finishes (according to the stats most shoppers jump out of checkout when they actually have to pay) or cancels a payment the reserved stock with an order will not be released and thus there is a risk that simple automation (or even many users) will run the shop out of stock.
> There will be orders which will never be paid but shown in commercetools Merchant Center dashboard as revenue - which is not true.
Not paid orders will falsely boost the concept of “best sellers” index of its products.

I do not know how small stock we should have or how many of failed payments you expect, but with a standard rate of failed payments and stock having a sensible quantity is not a problem. BTW unpaid orders expire and stock should be restored. 

> Creating an order does not allow you to modify the original cart anymore. What happens if a shopper forgot something and would like to change the cart just after the initiation of the payment?

Usually, you need to cancel an order and create another one.

> How to handle vouchers that can be applied only once but the shopper decided not to finish the payment and change the cart instead? It might require a new cart based on the old cart. The creation of a new cart with the same item might be an issue if an item had only stock = 1 and it has been used in not paid order already.

And here as well, usually, you need to cancel an order and create another one. I do not know how Commercetools work with vouchers for canceled orders but I expect the voucher will be still valid.  

I personally think the approach you suggest might be very harmful. Think about how the system behaves, in case you have an error on the asynchronous piece of code responsible for creating an order. What would be the user experience?  What do you will to if due to that error hundred of customers were charged but the order wasn't created? What will then customers do? call support or maybe even worse they will try to make another payment?

**Comment by butenkor** [comment]
> I do not know how small stock we should have or how many of failed payments you expect, but with a standard rate of failed payments and stock having a sensible quantity is not a problem. BTW unpaid orders expire and stock should be restored.

It is more about for example your competition or script kiddies which with a simple script can just run out your store out of stock, for all the products. 

> BTW unpaid orders expire and stock should be restored.

While you restore your stock customers during this time can not buy it. There are many articles where stock is limited.

> Usually, you need to cancel an order and create another one.

Canceled order just changes its order state but order statistically stays an order.

> I do not know how Commercetools work with vouchers for canceled orders but I expect the voucher will be still valid.

Canceled order does not give you back a voucher - as mentioned, it just changes its state. You would have to re-create and re-send the voucher to the customer.

> Think about how the system behaves, in case you have an error on the asynchronous piece of code responsible for creating an order. What would be the user experience? What will you do if due to that error hundred of customers were charged but the order wasn't created? What will then customers do? call support or maybe even worse they will try to make another payment?

If you followed the guide it also mentions [commercetools-payment-to-order-processor](https://github.com/commercetools/commercetools-payment-to-order-processor) which is an example implementation, which shows how you can ensure that for every successful payment you can always create asynchronously (lets say on schedule base, every 3 mins) an order. Implementation also covers error case and has retries in place. If you like, you can also do the same in a message/event driven architecture.

**Comment by jakinluk** [comment]
[commercetools-payment-to-order-processor](https://github.com/commercetools/commercetools-payment-to-order-processor) - I am not saying this code is not working. But what if there will be a bug introduced in future improvements or there will be something wrong with your infrastructure and you won't receive the notification about payment completion? The order won't be created until your infrastructure is back working again or after you fix an error. During that time customer have no order, just still the same, still non-empty cart they were charged for. Or I am missing something?

**Comment by butenkor** [comment]
> But what if there will be a bug introduced in future improvements

Then you fix it and make sure it never happens again ;)
The PSP notification delivery system as also the linked solutions here are build for resiliency. You can surely question everything but no-body in IT world will ever provide a 100% guarantee all the time. Thats why SLAs are mostly 99.8 and similar.

> Did you try to buy something over amazon.com or ebay? Both follow the "Order first approach"

Amazon and similar do not depend on PSPs and do not allow redirect payments which lead to many edge case issues like accidentally closed tabs. Also, Amazon does not allow to create an order as long as they do not have your credit card or bank data which has been already verified and can be charged any time. They do not have cases like: 
no payment data collected -> create order -> redirect user to PayPal -> user closes the tab or does not finish payment -> problem.

**Comment by jakinluk** [comment]
>Then you fix it and make sure it never happens again 
If you have introduced a bug in the code responsible for handling a successful payment notification and no orders are being created. before you fixed it you may have 1, 10 1000... affected customers, that will try to contact support, and some of them will retry the payment. 

> Amazon does not allow to create an order as long as they do not have your credit card or bank data which has been already verified and can be charged any time.

Of course, Amazon requires form you a payment method. It might be a new valid credit card or prepaid card without money on it or even your old no more valid card Amazon had saved in the past. Here is my order on amazon. I used my old card which appeared to be no more valid. 
<img width="854" alt="image" src="https://user-images.githubusercontent.com/10652855/216694966-3ec28fa6-6f7d-47d7-bd45-893198cf707c.png">

With Amazon and I believe it is the right approach after you provide all shipping details and choose a payment method, and click submit (by the way "place your order"), the order is created and the payment process is initiated. 

The same approach is valid whenever you introduce redirection to Paypal or 3d secure page. Of course - you must do everything that is possible to block invalid payment methods before creating an order. Payment processing with PayPal is often delayed, you just obtain the Billing agreement that will be used to complete the payment.  But still it does not mean there is enough money on the account. 
The other common scenario is to provide a delayed payment option when you place an order, you sent then a proforma invoice that has to be linked with an existing order.

> They do not have cases like:
no payment data collected -> create order -> redirect user to PayPal -> user closes the tab or does not finish payment -> problem.

And exactly these cases, with redirection, are the cases your approach is most vulnerable to. There are so many things that may happen in between. And for that case, you need to have the order as the trace of the process that had already started.

**Comment by butenkor** [comment]
We may just suggest when you could create an order but depending on your case, it is up to you when you do it. I explained our reasoning behind the suggestion. Is there still anything you would like to know or the ticket can be closed?

**Comment by jakinluk** [comment]
Thank you for the discussion. Please go ahead and close the ticket.
