### ISSUE TITLE
Issue with Icelandic(ISK) currency and Adyen not following the ISO standard.

### ISSUE THREAD

**Issue by hjalmar** [commercetools/commercetools-adyen-integration#1085]
I'm currently trying to handle Icelandic(ISK) currency with this extension. Adyen deviates from the standard and expects the cent amount to have 2 decimals while commercetools assumes 0. https://docs.adyen.com/development-resources/currency-codes (see the notes box)
![image](https://user-images.githubusercontent.com/304324/231220070-dcb5db2c-13c2-46d5-b038-9af275bf1537.png)

I have gotten it to work with a workaround of converting the cent amount by padding it with 2 decimals. It seems to work fine with the exception of it being formatted wrong in the commercetools admin. But I'm also not sure and why I'm creating this issue.

Is that the way to go or is there any other, more proper way to handle this case?

The actual cent amount in commercetools `2790`. So adyen expects it to be `279000` and why amountPlanned here is formatted as `279,000` because ISK does not have any decimals.
![image](https://user-images.githubusercontent.com/304324/231219038-7cfaaba4-a43c-40b2-b70b-a5ccf6a2c86c.png)

**Comment by hjalmar** [comment]
Anyone have any thoughts on my issue?

**Comment by butenkor** [comment]
Hi @hjalmar It does not matter what commercetools assumes since the amount passed to Adyen is taken as is from the payload the Adyen web-component JS generates. If amount does not have the required format please adjust your web components payload before you set it to commercetools.
