### ISSUE TITLE
On error write interfaceInteraction only once

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-adyen-integration#13]
When we receive error response from Adyen, we should check if the error has been already logged in `interfaceInteractions`. If yes, then don't add new `interfaceInteractions`. This will prevent unnecessary load on our platform in case someone tries to make a payment multiple times with wrong credentials.

**Comment by butenkor** [comment]
Hi @lojzatran Can it be closed? Also why would we check here with OR and not AND? https://github.com/commercetools/commercetools-adyen-integration/blob/7cc6018016f8c15f64ec23dc04544411280c9d09/extension/src/paymentHandler/payment-utils.js#L85-L87

**Comment by butenkor** [comment]
It can be closed once the web-components version is released.

**Comment by ahmetoz** [comment]
https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v5.0.0, I am closing the issue.
