### ISSUE TITLE
Consider implementing a concurrent `Promise.map` instead of using Bluebird only for this function

### ISSUE THREAD

**Issue by LEQADA** [commercetools/commercetools-adyen-integration#16]

**Comment by lojzatran** [comment]
Another benefit of using Blubird is performance: https://softwareengineering.stackexchange.com/questions/278778/why-are-native-es6-promises-slower-and-more-memory-intensive-than-bluebird

**Comment by LEQADA** [comment]
We are using bluebird only for `Promise.map`. We can implement our own `map` which will not be that slower than Bluebird 🙂

**Comment by emmenko** [comment]
> Another benefit of using Blubird is performance

It's a bit outdated 😅

> We can implement our own map which will not be that slower than Bluebird

💯
