### ISSUE TITLE
Remove an option to activate or deactivate 3D secure

### ISSUE THREAD

**Issue by butenkor** [commercetools/commercetools-adyen-integration#165]
Remove an option to activate or deactivate 3D secure by setting this variable here: https://github.com/commercetools/commercetools-adyen-integration/blob/77f9cbab55efe4ca40761666983d6f3244b35c87/extension/src/paymentHandler/creditCard/credit-card-make-payment.handler.js#L101

Instead, let it be handled by Adyen automatically through [Dynamic 3D secure](https://docs.adyen.com/payments-fundamentals/psd2-sca-compliance-and-implementation-guide#specifypreferenceinyourapirequest)

**Comment by ahmetoz** [comment]
The code is not valid anymore with https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v5.0.0, I am closing the issue.
