### ISSUE TITLE
Add UI tests for payment methods

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-adyen-integration#18]
Add UI tests for all payment methods.

**Comment by lojzatran** [comment]
Unfortunately with Cypress it is not possible to test Paypal payment.
There are 2 problems with paypal:
1) The Paypal login interface for automated testing is different from what I see as a user and sometimes it changes. This makes the test unreliable.
2) When Cypress logs in to Paypal, Paypal redirects user to a payment page. Unfortunately it also redirects the whole Cypress UI and test cannot continue. See: https://github.com/cypress-io/cypress/issues/1496

**Comment by lojzatran** [comment]
I guess for UI testing we need to use Selenium: https://www.npmjs.com/package/selenium-webdriver

**Comment by lojzatran** [comment]
Alternatives:
https://devexpress.github.io/testcafe/
http://nightwatchjs.org

**Comment by ahmetoz** [comment]
We have e2e tests with using chrome puppeteer with release v5.0.0
