### ISSUE TITLE
Add support for me/payments (getAvailablePaymentMethods is not accessible)

### ISSUE THREAD

**Issue by butenkor** [commercetools/commercetools-adyen-integration#187]
Me payments does not return `interfaceInteractions` which are required in order to present available payment methods to the user as described here: https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/IntegrationGuide.md#checkout-steps

Possible solution: copy value from `interfaceInteractions` to `payment.custom.fields.availablePaymentMethods`

See also: SUPPORT-8144

**Comment by butenkor** [comment]
It can be closed once the web-components version is released.

**Comment by ahmetoz** [comment]
https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v5.0.0
