### ISSUE TITLE
Add HTTP authentication

### ISSUE THREAD

**Issue by LEQADA** [commercetools/commercetools-adyen-integration#24]
Adyen can authorise using HTTP authentication to access the notification module. It is a good idea to use it since the endpoint will be public.
https://docs.adyen.com/developers/development-resources/notifications/set-up-notifications?redirect#step1receivenotifications

**Comment by ahmetoz** [comment]
As we have implemented #32 for the security of the notification, the ticket is not considered to be sth to implement in near future. Hereby I'm closing this issue.
