### ISSUE TITLE
Clarify if additionalData are needed for the response

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-adyen-integration#260]
According to this support ticket, `additionalData` field should be removed from `interfaceInteraction`: https://jira.commercetools.com/browse/SUPPORT-6715

However, `additionalData` might be useful for the shop as they contains data for additional logic and evaluation:
https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v52/payments__resParam_additionalData

We should clarify with Adyen if `additionalData` contains sensitive info and should be removed by our integration or only some fields should be removed, but not the whole `additionalData`.

**Comment by butenkor** [comment]
According to the ticket additionalData fields can be customized in Adyen back office. Do you still think that we have any TODOs here?

**Comment by lojzatran** [comment]
Yes, what I don't understand is that after they customize, they probably also want to see those customized fields in the response? Now we're removing `additionalData` from the response, therefore there's no way for the shop to get additionalData.

**Comment by butenkor** [comment]
Let's wait for the first customer case where `additionalData` is required for the front end. Then we can consider making it configurable. For now, we delete `additionalData` from the response.
