### ISSUE TITLE
refactor the processNotifications method

### ISSUE THREAD

**Issue by ahmetoz** [commercetools/commercetools-adyen-integration#272]
A structure of notification is described here:
https://docs.adyen.com/development-resources/webhooks/understand-notifications#notification-structure

<img width="839" alt="Screenshot 2020-05-08 at 15 13 20" src="https://user-images.githubusercontent.com/3469524/81409005-96aad780-913e-11ea-95ab-43b85153f592.png">

As we are not supporting SOAP on the notification module, we don't need to iterate notification request items as below method, because it will only be one request item.

https://github.com/commercetools/commercetools-adyen-integration/blob/18c39ed19c44a69a9df1b1281e16389b1776472c/notification/src/handler/notification/notification.handler.js#L8-L12

**Comment by butenkor** [comment]
As discussed for now it is not an issue and can be closed
