### ISSUE TITLE
fix makePayment interaction getters on additional payment handler 

### ISSUE THREAD

**Issue by ahmetoz** [commercetools/commercetools-adyen-integration#289]
From the comment of a PR: 

> Theoretically there could be multiple interfaceInteraction for makePayment, so I guess you should get the newest one. 

https://github.com/commercetools/commercetools-adyen-integration/blob/2b6b0c35c892e83bbebb1b2e96c2426f82d7e7eb/extension/src/paymentHandler/submit-payment-details.handler.js#L39-L41

> Is it better if you take the response from the custom field makePaymentResponse?

https://github.com/commercetools/commercetools-adyen-integration/blob/2b6b0c35c892e83bbebb1b2e96c2426f82d7e7eb/extension/src/paymentHandler/submit-payment-details.handler.js#L11-L14

**Comment by ahmetoz** [comment]
@lojzatran any update in here?

**Comment by lojzatran** [comment]
Not yet, we agreed we will discuss after finishing the e2e tests so I can show the case when you can have multiple interface interactions of the same type.

**Comment by lojzatran** [comment]
Closing the ticket because the issue does not occur on `makePayment`.
