### ISSUE TITLE
Consider using a template engine for e2e tests

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-adyen-integration#322]
Some parts of the HTML are repetitive. It's a good idea to have a template engine to have it DRY. This problem effects only e2e HTML templates.

**Comment by ahmetoz** [comment]
Honestly, I don't think this is the way to use it for one simple thing. Which will add additional complexity? I would rather not implement this. WDYT? @lojzatran

**Comment by lojzatran** [comment]
For now seems like not important. Maybe one day we will have more files that need this template engine, then we can add it.

**Comment by ahmetoz** [comment]
I would not add additional tasks into issue backlog if it's not an issue or technical debt, in this case this is not, I would go with closing the issue, WDYT?

**Comment by lojzatran** [comment]
Closing as it's not an issue but rather enhancement.
