### ISSUE TITLE
Consider passing an object instead of multiple arguments

### ISSUE THREAD

**Issue by LEQADA** [commercetools/commercetools-adyen-integration#39]
as suggested by @emmenko https://github.com/commercetools/commercetools-adyen-integration/pull/17#discussion_r262951944
For example:

```js
function getAddTransactionUpdateAction ({ type, state, amount, currency }) { // object instead of 4 different params
  return {
    action: 'addTransaction',
    transaction: {
      type,
      amount: {
        currencyCode: currency,
        centAmount: amount
      },
      state
    }
  }
}

getAddTransactionUpdateAction({ type: 'bla', state: 'bla', amount: 'bla', currency: 'bla' })
```

A benefit of this approach is that one doesn't need to presume the order of arguments. They just have to be in the object.

**Comment by ahmetoz** [comment]
This is already fixed in another commit, hereby I am closing the issue.

https://github.com/commercetools/commercetools-adyen-integration/blob/31266362c3804f483bdb324aacac887de20e0cba/notification/src/handler/notification/notification.handler.js#L169-L184
