### ISSUE TITLE
Add liveness and readiness probes

### ISSUE THREAD

**Issue by LEQADA** [commercetools/commercetools-adyen-integration#50]

**Comment by ahmetoz** [comment]
@LEQADA  could you please clarify that? Did you mean health endpoints for the modules?

**Comment by LEQADA** [comment]
We created k8s deployment yamls for both modules here https://github.com/commercetools/commercetools-adyen-integration/tree/k8s-deployment

The deployment doesn't have readiness and liveness probes. It needs to be discussed how they'll be implemented.
