### ISSUE TITLE
"How to run guide" is a dead link

### ISSUE THREAD

**Issue by molly-jones** [commercetools/commercetools-adyen-integration#509]
In the section called "Before You Begin," there is a link for "how to run guide" that is broken. 

The URL is https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/docs/HowToRun.md

I should clarify that the link from the table of contents is valid (https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/HowToRun.md), just the link in the text of the body seems to be malformed.

**Comment by lojzatran** [comment]
Hi @molly-jones thanks for pointing out the problem. We've fixed the links!
