### ISSUE TITLE
Document compliance of the integration with PCI DSS credit card requirements

### ISSUE THREAD

**Issue by butenkor** [commercetools/commercetools-adyen-integration#55]
Current integration supports credit card payments but it does not process sensitive credit card data thus is compliant with PCI DSS requirements. We should mention it in our documentation [here](https://github.com/commercetools/commercetools-adyen-integration#supported-payment-methods):

`Credit card with 3DS payment ([PCI DSS compliance](link to an anchor of credit card integration doc))`

**Comment by ahmetoz** [comment]
@butenkor could you please clarify what needs to be documented?
