### ISSUE TITLE
Document which (types of) payment methods are supported

### ISSUE THREAD

**Issue by ab294** [commercetools/commercetools-adyen-integration#569]
Please document which payment methods or categories of payment methods are supported by this module.

From looking at the code, the following are mentioned in the tests:
- Credit and debit cards
- SEPA
- PayPal
- Klarna
- iDeal
- Some Giftcards (Givex & SVS)

At a guess I'd say all payment methods that don't require a redirect are supported? Any redirect payment methods require a specific payment handler?

**Comment by ahmetoz** [comment]
Hi @ab294 

Thanks for the documentation suggestion, as stated in the main [readme](https://github.com/commercetools/commercetools-adyen-integration#commercetools-adyen-integration)

> For a list of all payment methods with an available component, refer to [Supported payment methods](https://docs.adyen.com/checkout/supported-payment-methods).

For the test cases, we tried to cover the parts that are a must for the codebase so it does not mean if there is no test in the codebase specific to this payment method we are not supporting it. 

As we are using the Adyen web components (starting with [v5.0.0](https://github.com/commercetools/commercetools-adyen-integration/releases)), all payments supported by Adyen web components are supported also by integration. 

You might check our [integration documentation](https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/WebComponentsIntegrationGuide.md#integration-guide) for the details.

**Comment by ab294** [comment]
Thanks for that, that does help but apologies I wasn't clear enough in my question.
I noticed there is a custom payment handler for Klarna. Which payment methods are supported using the existing payment handlers and which would need a new custom payment handler?
As a guess from looking at the Adyen documentation any Redirect Payment Method will require a custom payment handler?

**Comment by ahmetoz** [comment]
> custom payment handler for Klarna
What do you mean by custom payment handler? 

In terms of Adyen web components and klarna, it's a payment type that requires a redirect, the merchant server should [submit the additional details](https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/WebComponentsIntegrationGuide.md#step-5-submit-additional-payment-details
), for specific payment types like klarna payment the extension module could help to collect the line item details on [make a payment](https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/WebComponentsIntegrationGuide.md#klarna-payment) step.

Additional Refs:
https://docs.adyen.com/online-payments/components-web#step-5-additional-payment-details
https://docs.adyen.com/payment-methods/klarna/web-component

**Comment by ab294** [comment]
Hey @ahmetoz, thanks for your speedy reply :)

This file is a custom payment handler specifically for Klarna: [klarna-make-payment-handler.js](https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/src/paymentHandler/klarna-make-payment.handler.js)
The core of my question is for what types of payment method do you need to create a new payment handler

**Comment by ahmetoz** [comment]
Oh, I see now what you mean by custom payment handler :) 

First of all, the users of the extension module do not need to create a payment handler. 

The klarna-make-payment-handler is extending the main payment-handler and can add the line item details for you if the payment is added to a cart. 

As said in the klarna payment part: https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/WebComponentsIntegrationGuide.md#klarna-payment

By default, the extension module will populate lineItems for you but in case you want to define your own values include lineItems in your `makePaymentRequest`.

I hope this answers your question?

**Comment by ahmetoz** [comment]
Hi @ab294, I assume your questions are answered.

The issue can be reopened at any time by adding a comment in case you have further questions or comments on this topic.
Thanks!
