### ISSUE TITLE
Extension and Notification package names are not unique

### ISSUE THREAD

**Issue by mariuszkos** [commercetools/commercetools-adyen-integration#572]
The extension and notification modules are packages in their own right, but they have the same package name `commercetools-adyen-integration`. 

Can the names of extension and notification packages names be changed in package.json? For example, `commercetools-adyen-integration-extension` and `commercetools-adyen-integration-notification`.

**Comment by ahmetoz** [comment]
Hi @mariuszkos, 

Hmm, yes, it makes sense to choose unique names as the package name.

What about `commercetools-adyen-integration/extension` and `commercetools-adyen-integration/notification` ?

**Comment by ahmetoz** [comment]
Hi @mariuszkos, before making this change we want to know more about these 2 questions:
- Why this change is required?  
- What is the use case?

**Comment by mariuszkos** [comment]
Hi @ahmetoz, in the future we would like to be able to publish these two modules (Extension and Modification) in a private npm registry with as few changes as possible. As it stands, we can't do that because of non-unique package names.

We have a way to deal with this for now that doesn't involve publishing to a private npm registry, but AFAIK this is generally considered good practice.

**Comment by ahmetoz** [comment]
Hi @mariuszkos, For the npm practice you are right, we just wanted to know the use case 👍🏽 

The changes are now merged to master branch with PR: https://github.com/commercetools/commercetools-adyen-integration/pull/573

I'm closing the issue for now.

**Comment by mariuszkos** [comment]
Thanks @ahmetoz.
