### ISSUE TITLE
Faulty try/catch in notification processing

### ISSUE THREAD

**Issue by GergelyToth** [commercetools/commercetools-adyen-integration#602]
https://github.com/commercetools/commercetools-adyen-integration/blob/a63624fb94d294f4ec50ae99e06a142e922c2ed3/notification/src/utils/parser.js#L15-L20

If the `metadata.commercetoolsProjectKey` is not present in the `additionalData`, but the property itself exists in the notification, this try/catch will not fail, and instead will pass `undefined` as project key, which will throw the following error:

```
Configuration is not provided. Please update the configuration. ctpProjectKey: [undefined]
```

**Comment by lojzatran** [comment]
Hi @GergelyToth,

Thank you for reporting this potential issue. I had a look at the code and here's what I found out:

The notification module requires `metadata.commercetoolsProjectKey` to work correctly as it needs to save the notification to the matching payment in the project. Without `commercetoolsProjectKey` it cannot determine the CTP project. Therefore we expect to have `metadata.commercetoolsProjectKey` in every notification.

Can you write in which type of notification you get the problem and also post the notification here so we can investigate further?

Best regards,
Lam Tran

**Comment by GergelyToth** [comment]
Hi Lam,

I have not been able to successfully retrieve the full notification from the error message that was throw. 
The integration is successfully working on Apple Pay, Google Pay and card payments, but it fails on Paypal authorization notifications in our end, and unfortunately, even after contacting Adyen to request the full notification, they could not provide the necessary information.

Kind regards,
Greg

**Comment by butenkor** [comment]
@GergelyToth I had a talk with Adyen and got the following reply:
```
At time of sending the notification we have for some local payment methods not the required info in that specific system.
There is a setting “skip sending on PAL” that fixes the issue for these local payment methods. 
Support can enable that setting on the notification endpoint of the merchant. 

If you/they could please request this setting on the notification endpoint it would be great. 
I now don’t have the right context of the merchant (accounts, etc.)
```
Let us know if this helped.

**Comment by GergelyToth** [comment]
Hi,

The example notification, fired from the Adyen server notification backend is failing for the reason mentioned by my first comment. The try/catch validation check doesn't catch the project key missing, and is treating the notification as it something still recoverable, and should be processed by it, and will pass the `undefined` key down, where it fails on: https://github.com/commercetools/commercetools-adyen-integration/blob/a63624fb94d294f4ec50ae99e06a142e922c2ed3/notification/src/config/config.js#L17

Please find the example notification and the server response below:

``json
{
    "live": "false",
    "notificationItems": [
        {
            "NotificationRequestItem": {
                "additionalData": {
                    "expiryDate": "12/2012",
                    " NAME1 ": "VALUE1",
                    "authCode": "1234",
                    "cardSummary": "7777",
                    "shopperIP": "127.0.0.1",
                    "totalFraudScore": "10",
                    "hmacSignature": "Rzqg7KN8z5zbSZV31fOEyRbFx7pX1JSSvLfQxlhoAnk=",
                    "NAME2": "  VALUE2  ",
                    "fraudCheck-6-ShopperIpUsage": "10"
                },
                "amount": {
                    "currency": "EUR",
                    "value": 10100
                },
                "eventCode": "AUTHORISATION",
                "eventDate": "2021-03-17T18:21:43+01:00",
                "merchantAccountCode": "MERCHANTACCOUNTCODE",
                "merchantReference": "8313842560770001",
                "operations": [
                    "CANCEL",
                    "CAPTURE",
                    "REFUND"
                ],
                "paymentMethod": "visa",
                "pspReference": "test_AUTHORISATION_1",
                "reason": "1234:7777:12/2012",
                "success": "true"
            }
        }
    ]
}
```
​
GCP server log
```json
{
  "insertId": "1031jfig68jdnht",
  "jsonPayload": {
    "pid": 1,
    "name": "ctp-adyen-integration-notifications",
    "notification": [
      {
        "eventDate": "2021-03-17T18:21:43+01:00",
        "eventCode": "AUTHORISATION",
        "success": "true",
        "pspReference": "test_AUTHORISATION_1"
      }
    ],
    "v": 0,
    "level": 50,
    "hostname": "commercetools-adyen-integration-notification-765bcdd8d6-ctzcp",
    "err": {
      "stack": "Error: Configuration is not provided. Please update the configuration. ctpProjectKey: [undefined]\n    at Object.getCtpConfig (/app/src/config/config.js:18:11)\n    at getCtpProjectConfig (/app/src/utils/parser.js:32:31)\n    at handleNotification (/app/src/api/notification/notification.controller.js:17:32)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Server.<anonymous> (/app/src/server.js:14:9)",
      "message": "Configuration is not provided. Please update the configuration. ctpProjectKey: [undefined]",
      "name": "Error"
    },
    "msg": "Unexpected exception occurred."
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "namespace_name": "dev",
      "project_id": "development",
      "location": "europe-west2",
      "cluster_name": "web-app-nonprod-infra",
      "pod_name": "commercetools-adyen-integration-notification-765bcdd8d6-ctzcp",
      "container_name": "services"
    }
  },
  "timestamp": "2021-03-17T17:21:43.065Z",
  "severity": "INFO",
  "labels": {
    "compute.googleapis.com/resource_name": "gke-web-ap-web-ap-99e2c39c-wwmc",
    "k8s-pod/pod-template-hash": "765bcdd8d6",
    "k8s-pod/part-of": "e-commerce-frontend",
    "k8s-pod/component": "services",
    "k8s-pod/name": "commercetools-adyen-integration-notification",
    "k8s-pod/environment": "dev"
  },
  "logName": "projects/development/logs/stdout",
  "receiveTimestamp": "2021-03-17T17:21:46.020487590Z"
}
​
{
  "textPayload": "130.211.0.196 - dev-adyen-ct [17/Mar/2021:17:21:43 +0000] \"POST /api/checkout-notification/ HTTP/1.1\" 500 5 \"-\" \"Adyen HttpClient 1.0\"\n",
  "insertId": "saxugng64nred7",
  "resource": {
    "type": "k8s_container",
    "labels": {
      "project_id": "development",
      "pod_name": "commercetools-adyen-integration-notification-765bcdd8d6-ctzcp",
      "location": "europe-west2",
      "container_name": "nginx",
      "namespace_name": "dev",
      "cluster_name": "web-app-nonprod-infra"
    }
  },
  "timestamp": "2021-03-17T17:21:43.065917446Z",
  "severity": "INFO",
  "labels": {
    "k8s-pod/pod-template-hash": "765bcdd8d6",
    "k8s-pod/component": "services",
    "k8s-pod/part-of": "e-commerce-frontend",
    "compute.googleapis.com/resource_name": "gke-web-ap-web-ap-99e2c39c-wwmc",
    "k8s-pod/name": "commercetools-adyen-integration-notification",
    "k8s-pod/environment": "dev"
  },
  "logName": "projects/logs/stdout",
  "receiveTimestamp": "2021-03-17T17:21:46.019418979Z"
}
```

**Comment by butenkor** [comment]
Hello @GergelyToth , we will fix the unexpected issue as the validation should have failed sooner and we should not have passed `undefined` further. Fixing it though will not fix your problem as we still need `commercetoolsProjectKey` in the notification. Previously you mentioned that it was only absent in PayPal case and now it is also absent for visa credit card payment?

**Comment by GergelyToth** [comment]
Hi @butenkor,
Thank you for the reply! Yes I am aware that it won't necessarily fix the issue, but currently Adyen is saying that we should be receiving the `commercetoolsProjectKey` with the `Skip sending on PAL` setting, but it is not going to take effect until we fix all notification errors.

```
The reason that you're currently not receiving any notifications is that your endpoints aren't accepting notifications properly. You can verify this in the Customer Area by going to Account > Server communication > Troubleshoot. Please make sure to acknowledge every notification with [accepted]. You can read more about this here. 

When this doesn't happen, we stop sending notifications to your endpoint and queue them instead. Once your endpoint is accepting notifications properly again, the queue of notifications will be flushed and you'll still receive the notifications you're currently waiting for.
```

The problem is currently occurring on all Paypal notifications, and all Credit/Debit Card Charge notifications. On all else, Authorization notification, the metadata is correctly passed along, but until this issue is fixed, we do not know wether the issue is only because of the notification server is not accepting _all_ notifications, or Adyen is loosing the key somewhere in the process.

**Comment by butenkor** [comment]
I see. The confusing part is that according to Adyen `Skip sending on PAL` setting should prevent the send out of invalid notifications so you should get only the one with the required data now. Maybe until we have a fix released (this or next week) Adyen/You can empty the notification queue in Adyen back office and see if it works?

**Comment by GergelyToth** [comment]
I have tried to empty all notifications, and they resulted in sending them onto the server again and failing. We had to set up the basic notification system without the `Skip sending to PAL` setting, in order to have our system running again partially.
Would you know an ETA when the patch for the fix will be out?

**Comment by butenkor** [comment]
@GergelyToth We are working currently on it so most probably this week or latest Monday.
