### ISSUE TITLE
Concerns of the Extension module

### ISSUE THREAD

**Issue by mariuszkos** [commercetools/commercetools-adyen-integration#608]
Hi,

We're We've got the Extension module up and running as an Azure Function and registered as an API extension with payment as trigger.

Let's suppose I make a call to the /payments endpoint in CT to get a list of payment methods. CT queries Extension, Extension queries Adyen, but Adyen is not happy with the request and sends back a 400 response. From what I could see, Extension only has validation logic on the request from CT, but does not inspect the result from Adyen, so paymentHandler.handlePayment returns { success: true }. 

Should Extension always return 200 responses to CT even in cases like this? My understanding is that CT will persist the payment information if it receives a 200 response from all API extensions. If there is a 4xx response in the synchronous flow from Adyen, shouldn't Extension also be sending that response code to CT?

Thanks

**Comment by butenkor** [comment]
> If there is a 4xx response in the synchronous flow from Adyen, shouldn't Extension also be sending that response code to CT?

The intention was to give an integrator/shop an ability to get all the error details so that it can be easily analysed in case of the issues. If we would reject with non 200 we would not be able to persist the Adyen request/response.

**Comment by butenkor** [comment]
@mariuszkos Is it still an issue for you?

**Comment by mariuszkos** [comment]
@butenkor Thank you for clarifying and pointing me to the error handling page. This issue can be closed now.
