### ISSUE TITLE
Extension incompatible with /me/payments endpoint

### ISSUE THREAD

**Issue by zackpollard** [commercetools/commercetools-adyen-integration#62]
When trying to use this extension alongside the /me/payments endpoint in order to create and process a payment, the extension throws an error due to being unable to specify an interfaceId from the My Payments version of the endpoint. Did some quick testing and removed the interfaceId validation from the extension and generated a random UUID instead and then the payment processes fine. What would need to be done in order to get this working properly with the my payment endpoint? It seems like you'd want to be able to specify the interfaceId from the client side in order to get the benefit of de-duplicating payments.

**Comment by LEQADA** [comment]
Hi @zackpollard. Thank you for the issue.
`interfaceId` is used as an Adyen `reference` (see https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v41/payments).
According to the documentation `reference` should be an order number. So we leave it to the shop implementation to use as an order number whatever they want.
`MyPayments` endpoint currently doesn't support `interfaceId` field. Not sure why.
I'd ask it to the commercetools platform support if you didn't yet.

**Comment by zackpollard** [comment]
Yea, we have a support issue raised currently around this issue. It makes sense for it to be an order number, however i'm not sure where we should get that from as we can't create the order before creating the payment object as the MyOrders endpoint doesn't allow adding a payment after you've created the order from the cart. If we are going down the route of using the "me" endpoints for all of our calls (which we would prefer to do) then it seems like the flow we are forced into doing is:
  1. Have cart with items in it
  2. Create MyPaymentDraft and submit to commercetools for processing based on value of cart
  3. Attach payment to cart
  4. If payment wasn't a failure, convert cart to order and set the status on that order as ready to fullfill

As far as I can tell this is our only option if using the my endpoints. Is there a flow that you guys had in mind when building this extension? If so what would that ideal flow be?

**Comment by LEQADA** [comment]
Right. I understand the problem now. We need to talk to the platform team and come up with a solution.

**Comment by zackpollard** [comment]
Following on from conversations we have had, we are looking to pick up this piece of work shortly. We have been advised that the best course of action would be to replace the use of the interfaceId field with a unique identifier that is specified within the custom type that already exists on the payment object. What would you advise that we call this new field on the custom type? Would interfaceId still make sense or is paymentReference or something else more appropriate? Also are you happy for us to pick up this work at this point in time.
