### ISSUE TITLE
Impossible to submit payment details twice

### ISSUE THREAD

**Issue by Fifciu** [commercetools/commercetools-adyen-integration#623]
It is impossible to submit payment details twice, so I cannot properly go through 3DS2 Auth process if it requires 2 actions (case from test cards).

## Why would anyone need to submit payment details twice?
3DS2 might require 2 challenges:
- IdentifyShopper
- ChallengeShopper

Unfortunately, one condition from the code prevents app from sending second `submitAdditionalPaymentDetailsRequest` if `submitAdditionalPaymentDetailsResponse` already exists. So it is impossible to send results of `ChallengeShopper` to the Adyen.

We can reproduce a problem with a card like `5454 5454 5454 5454` or `4917 6100 0000 0000` from this page: https://docs.adyen.com/development-resources/test-cards/test-card-numbers#test-3d-secure-2-authentication

## What can we do?
There are 2 ways. One, which I applied locally, is to get rid of `submitAdditionalPaymentDetailsResponse` check in `payment-handler.js`:
```js
if (
    paymentObject.custom.fields.makePaymentResponse &&
    paymentObject.custom.fields.submitAdditionalPaymentDetailsRequest //&&
    // !paymentObject.custom.fields.submitAdditionalPaymentDetailsResponse
  )
    handlers.push(submitPaymentDetailsHandler)
```

With this simple change - it works properly.

Another way, would be creating a new fields for second `submitAdditionalPaymentDetailsRequest` and `submitAdditionalPaymentDetailsResponse` or maybe make them arrays. However, I am pretty pessimistic about that because I see no need to keep this data in CT.

**Comment by ahmetoz** [comment]
Hey @Fifciu 

Yes it's prevented with code, 
I just wonder, did you unset custom field `submitAdditionalPaymentDetailsResponse` ?
 
See: https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/WebComponentsIntegrationGuide.md#action-response-1

Let me know if the documentation is not clear at this point, so we could improve it.

**Comment by butenkor** [comment]
@Fifciu Please check if you followed the instructions as stated by @ahmetoz above as your case has been also taken into account by the integration. If you remove the check as suggest in your PR you might run into the issue that on any payment object changes on commercetools an integration would do unnecessary/failing submitAdditionalPaymentDetails requests to Adyen.

**Comment by Fifciu** [comment]
Indeed, now I see it. I've just made a test where I clear a value of `submitAdditionalPaymentDetailsResponse` if it is present during setting `submitAdditionalPaymentDetailsRequest` and it works fine. Thanks

**Comment by milindsingh** [comment]
@Fifciu I am also facing same issue. Can you share the exact fix in code ? Thanks

**Comment by Fifciu** [comment]
@milindsingh So during setting value of `submitAdditionalPaymentDetailsRequest` I am checking if `submitAdditionalPaymentDetailsResponse` is already set - if so I am adding an action to clear it.

```js
actions.push({
      action: 'setCustomField',
      name: 'submitAdditionalPaymentDetailsResponse'
    });
```

**Comment by ahmetoz** [comment]
Hey @milindsingh did you follow the integration documentation ?  https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/WebComponentsIntegrationGuide.md#action-response-1 
I wonder if you have a suggestion to improve it ?

@Fifciu thanks for the reply 🙏🏽
