### ISSUE TITLE
Remove obsolete data from interface interactions

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-adyen-integration#63]
Interface interactions contains a lot of unnecessary data. Revise and save only info which are useful.

**Comment by zackpollard** [comment]
Is there any planned work on this as currently the extension module adds the api key in the interface interactions which are accessible when retrieving a payment using the manage_my_payments scopes. Not sure that interface interactions should be accessible by users at all, but they are currently so getting this fixed is fairly important for us as obviously we don't want to have our adyen API keys accessible to the customer

**Comment by LEQADA** [comment]
Hi @zackpollard. Thank you for the report. i kindly ask you to avoid discussing sensitive information in public resources. Instead you could use our support portal https://support.commercetools.com
:slightly_smiling_face:

**Comment by zackpollard** [comment]
@LEQADA Yes of course, I've deleted the comment and will raise a support ticket in the morning.
