### ISSUE TITLE
Does it work with standard timeoutInMs? (2000ms)

### ISSUE THREAD

**Issue by Fifciu** [commercetools/commercetools-adyen-integration#632]
Hello,
I am not sure if it is possible to work with Extension module with default maximum `timeoutInMs` value which is `2000 ms`.
![image](https://user-images.githubusercontent.com/30155292/112166459-efb51a00-8bef-11eb-8189-0cc511d24659.png)

I see, you used `10 000 ms` in provided api-extension.js: https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/resources/api-extension.json

However, it is too demanding to have that big timeout. I had to change it to `2000 ms`. To set bigger value, we have to contact Support team (as docs say). I think it might be unacceptable if Adyen extension will be widely used by merchants. 

2000ms looks fine for Cards and related operations. But it looks like PayPal takes much more. I am currently working on it and it looks like maybe 5% of responses to `makePaymentRequest` are proper.

I wonder if maybe I am doing something wrong or it just requires 10s timeout?

**Comment by butenkor** [comment]
Increasing the limit is just our recommendation and you can try to work with defaults. Same as you we noticed during the integration that sometimes it might take a bit longer and then we would rather wait than have a failed request. One could expect from production environment a reply within 2 sec. but considering that commercetools talks to the integration, we talk to Adyen and Adyen might have to talk to 3rd parties like PayPal before answering us, it seems reasonable to be not to strict on the timeouts. Also, consider that PSPs sandbox environments are in general slower.

**Comment by Fifciu** [comment]
Got it.

Now, I wonder. What benefits do we have from having it as a CT Extension? Wouldn't it be better to write it as a simple node app? I am trying to find a different solution than forcing each merchant to ask support for an increased timeout limit.

**Comment by butenkor** [comment]
> What benefits do we have from having it as a CT Extension?

Just to name some of them:
- It's touchpoint independent. It does not matter from which channel (mobile App, desktop, me-endpoints etc.) you make a payment in commercetools -> it will be handled/validated in the same manner
- Easier to integrate. For front end it is a single request only to commercetools and you do not need know Adyen API details
- In case of validation issues, payment change can be prevented by commercetools centrally
- Another service or merchant center custom application which handles charges/refunds can just create a refund transaction in commercetools which will be automatically processed by the extension and would return a result right away

> Wouldn't it be better to write it as a simple node app?

You can and we used this approach also in the past (when API-Extension was not available yet). Here some examples:
https://github.com/commercetools/commercetools-paypal-plus-integration
https://github.com/commercetools/commercetools-payone-integration
It is just less elegant, a bit more complex as it needs to expose eventually more public endpoints and without the benefits previously mentioned.

Note that in your "simple node app" you will eventually have to use higher timeouts too as the majority of time you will spend talking to Adyen/3rd party.

> I am trying to find a different solution than forcing each merchant to ask support for an increased timeout limit.

Why is it an issue? Increasing timeout does not mean you will always need more than 2 sec. It just there to cover edge cases or those eventual 5% you mentioned. As I said - try it out on production and check if increase is required at all.

**Comment by butenkor** [comment]
@Fifciu Can the issue be closed?

**Comment by Fifciu** [comment]
Yes, thanks for helpful information
