### ISSUE TITLE
Clarify 'authorization' status with Adyen

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-adyen-integration#64]
When notification module receives a notification with type 'Authorization', it creates a new transaction with type 'Authorization'. In this case, it should update Charge transaction instead as for Adyen, 'authorization' means charge. 

Task: clarify the statement above with Adyen and update the modules accordingly.

**Comment by zackpollard** [comment]
Hey, is there any chance that this can be prioritised and followed up with adyen? It doesn't make sense to have two separate transactions on the payment when the card has only been charged once. Would be preferable if we could just update the charge transaction.

**Comment by butenkor** [comment]
After clarification with Adyen if transaction of type `Charge` exists in CTP then notification from Adyen with type `Authorization` should result in an update of `Charge` transaction status.

It is still unclear what notifications we would receive if we would first create authorisation/reservation with Adyen and charge it later (not really relevant for now as this process is not supported yet, see: #78)

**Comment by butenkor** [comment]
_Note: it does not matter if transaction in CTP is of type `Charge` or `Authorization` as request to Adyen will alsways look the same. It's back office setting within Adyen which decides if our request will end up as valid reservation or charge right away._ 

## Current process:

**Adyen's AUTOCAPTURE is active**:
1. We process CTP `Charge` transaction and send credit card payment to Adyen
2. On successful authorisation Adyen will send notification with eventCode `AUTHORISATION`
3. Notification module will add new transaction with type `Authorization`

**Adyen's MANUAL CAPTURE is active**:
1. We process CTP `Charge` transaction and send credit card payment to Adyen
2. On successful authorisation Adyen will send notification with eventCode `AUTHORISATION`
3. Notification module will add new transaction with type `Authorization`
4. On successful manual capture Adyen will send notification with eventCode `CAPTURE`
5. Notification module will update transaction status of transaction with type `Charge`

## New process:

By default we should expect CTP transaction to be supplied by the user with type `Authorization` only (right now it is `Charge`). This change would allow us to process transactions as follows:

**Adyen's AUTOCAPTURE or MANUAL CAPTURE is active**
1. We process CTP `Authorization` transaction and send credit card payment to Adyen
2. On successful authorisation Adyen will send notification with eventCode `AUTHORISATION` which will change status of existing `Authorization` transaction.
3. On successful manual capture Adyen will send additional notification with eventCode `CAPTURE` which will result in addition of new transaction of type `Charge` with the status from notification.

**Comment by butenkor** [comment]
@zackpollard Would the above new process also meet your expectations?

**Comment by zackpollard** [comment]
Hey @butenkor 

So in the case of auto-capture, we would simply just see the `Authorization` transaction and never see `Charge`? This sounds like a much better solution to me and would meet our expectations of the extension and notification modules. Thanks for looking into this.

**Comment by butenkor** [comment]
Hi @zackpollard. Yes, you would see both `Charge` and `Authorization` only if manual capture was used. It also means that new process would be a breaking change as you front end would need to create first transaction of type `Authorization` and not `Charge`
