### ISSUE TITLE
Running extension and notification module in AWS Lambda

### ISSUE THREAD

**Issue by zackpollard** [commercetools/commercetools-adyen-integration#65]
Currently both the extension and notification module have to be run as an HTTP endpoint, however the commercetools platform provides the option to run API extensions on AWS Lambda. We would like to use this option if possible, however this would require some changes to the way the modules currently work. Is this something you are looking to eventually build for these modules? If not, would it be something you would be willing to accept a pull request for? If neither of these are an option we will likely end up building a wrapper around the module to call the internal HTTP endpoint, however we would prefer to have a more integrated solution.

**Comment by zackpollard** [comment]
Following from conversations we have had, we are now looking at picking up this piece of work. Is this alright with your team and have you got any input into the way you would prefer this to be built before we go ahead and do the work? We are going to start looking into how we would do this today as it is now a priority for us.

**Comment by LEQADA** [comment]
Thank you for the issue @zackpollard. It's a good idea to make it serverless. 
Could you share the concept of how you see the integration in a serverless environment?

**Comment by zackpollard** [comment]
@LEQADA We are currently halfway through the implementation of this. What we were envisioning is that the lambda will be invoked and things such as ensureResources will run on the first cold start of the lambda, but won't run on following invocations (for that instance of the lambda). We have currently abstracted the logic out of the payment controller and into a payment handler, the payment controller will then just map the HTTP request to what the payment handler expects, and the lambda will have a similar class doing the same thing. We should have a PR ready sometime next week I imagine, I can create a draft PR for now if you would like to keep track of the ongoing work that we are doing. This is just for the extension module right now, but we will do much of the same work over in the notification module once we are done with the extension.

**Comment by LEQADA** [comment]
Sounds good! No need for a draft. Thank you again for initiative. 🙂

**Comment by zackpollard** [comment]
Both of these modules now support running inside a lambda, so i'm going to close this issue 😃
