### ISSUE TITLE
Fill payment name, method fields

### ISSUE THREAD

**Issue by Fifciu** [commercetools/commercetools-adyen-integration#657]
Hello,
I wonder if we could fill fields like `Payment name` and `Payment method` in Commercetools' payment from the `ctp-adyen-integration`. I imagine it could be very useful for the merchant's team to have information if it is a card, card with 3ds, paypal, klarna or smth different.

![image](https://user-images.githubusercontent.com/30155292/115198869-dc17a900-a0f2-11eb-8070-ab997934f8f6.png)

Currently, I have to copy `Interaction ID` and find it in Adyen's dashboard. I imagine some people might have access to the orders but not necessarily should have access to Adyen's dashboard. That's why we should add it.

Another reason is readability.

As we save the payload of `makePaymentRequest` in CT - there is a field `paymentMethod.type` which tells us what kind of payment we've used. It might be pretty easy to develop this feature with that.

I also wonder, what should we do with other fields like `Payment provider ID`, `Payment state`, `PSP Status Code` & Description?

**Comment by ahmetoz** [comment]
Hi @Fifciu 

Thanks for suggesting enhancements based on the merchant center users, normally we tend to use the least info (for now only required fields) that would be enough to complete payment within the integration. 

> As we save the payload of makePaymentRequest in CT - there is a field paymentMethod.type which tells us what kind of payment we've used. It might be pretty easy to develop this feature with that.

We need to discuss the team and need to consider all consequences for that change. After that, we could plan and implement those changes without breaking any existing functionality. 

Additional note, those fields could be also added to payment by sending those actions to payment.
https://docs.commercetools.com/api/projects/payments#set-methodinfoname
https://docs.commercetools.com/api/projects/payments#set-methodinfomethod
and others.

But I might also wait for this workaround in the case when we decide to add those enhancements, you might need to change the code. Do you have any urgency for those changes? 
 
> I also wonder, what should we do with other fields like Payment provider ID, Payment state, PSP Status Code & Description?

What do you mean by what should we do? Do you have a use case scenario that you need to use so we could discuss based on?

**Comment by butenkor** [comment]
@Fifciu In addition to what @ahmetoz wrote did you notice that within "View PSP transaction log" in your screenshot one can lookup the payment method too?

**Comment by Fifciu** [comment]
> Additional note, those fields could be also added to payment by sending those actions to payment.
https://docs.commercetools.com/api/projects/payments#set-methodinfoname
https://docs.commercetools.com/api/projects/payments#set-methodinfomethod
and others.

That could be a nice workaround for me, thanks. However, in my opinion, it should be a part of the `commercetools-adyen-integration` so it would always populate these fields - not only for developers with my module.

> Do you have any urgency for those changes?
Agencies are asking about it. They feel like my module is incomplete.

> What do you mean by what should we do? Do you have a use case scenario that you need to use so we could discuss based on?
I meant that I am not sure what kind of data we should put in these fields but it is worth investigating. 

> did you notice that within "View PSP transaction log" in your screenshot one can lookup the payment method too?
Yes, for me as a creator of Vue Storefront Module for Adyen & CT - it is pretty straightforward. Unfortunately, I am afraid it won't be for every developer/moderator - that's why filling fields mentioned in the issue would increase the user experience.

**Comment by butenkor** [comment]
Would it be enough if we would just set "Payment method" since we have no info on the "Payment name" from Adyen? Also, we would leave it up to the user and make it configurable over the env vars like: "setPaymentMethod": true|false.

**Comment by Fifciu** [comment]
I feel like `Payment name` could be a value from hardcoded map like:
```js
const paymentMethodToName = {
  scheme: 'Credit Card',
  pp: 'PayPal',
  klarna: 'Klarna',
  gpay: 'Google Pay',
  // ...
};
```

So `Payment method` could be a pure value which is passed to `paymentMethod.type` (e.g. `scheme`) and `Payment name` could be a more readable value from the map above (e.g. `Credit Card`).

What do you think about this approach?

**Comment by butenkor** [comment]
We would like to avoid hard coding payment specific mapping as by design the integration is payment method agnostic which means that any newly added web-component based Adyen payment method will be supported by this integration out of the box. Otherwise we would need to change the integration every time a new payment method is added.

**Comment by butenkor** [comment]
An alternative would be that we could hard code the current mapping and one could override the mapping or add new entries thorough the existing env var JSON configuration. Override would mean that you need to define only new mappings or the one that needs to be overridden as the rest would be used as already hard coded, wdyt?

**Comment by butenkor** [comment]
@Fifciu Any updates/thoughts from you side?

**Comment by Fifciu** [comment]
> An alternative would be that we could hard code the current mapping and one could override the mapping or add new entries thorough the existing env var JSON configuration. Override would mean that you need to define only new mappings or the one that needs to be overridden as the rest would be used as already hard coded, wdyt?

It sounds well for me. I would go for it
