### ISSUE TITLE
Support for Adyen v67 API

### ISSUE THREAD

**Issue by Fifciu** [commercetools/commercetools-adyen-integration#658]
Hello,
I've used to work on integration with v52 API of Adyen. However, I see now, we should use the newest version of both Web Drop-In and Adyen's API. That's why I am trying to apply support for v67 (latest) version of API.

The first difference I found is that I cannot pass any additional (not specified in doc) property anymore because Adyen throws a validation error. The thing is you extend `submitAdditionalPaymentDetails` with `applicationInfo` which is redundant field - not possible to pass validation anymore in the newest version of API:
```ts
function submitAdditionalPaymentDetails(
  merchantAccount,
  commercetoolsProjectKey,
  submitAdditionalPaymentDetailsRequestObj
) {
  const adyenCredentials = config.getAdyenConfig(merchantAccount)
  extendRequestObjWithMetadata(
    submitAdditionalPaymentDetailsRequestObj,
    commercetoolsProjectKey
  )
  extendRequestObjWithApplicationInfo(submitAdditionalPaymentDetailsRequestObj)
  return callAdyen(
    `${adyenCredentials.apiBaseUrl}/payments/details`,
    merchantAccount,
    adyenCredentials.apiKey,
    submitAdditionalPaymentDetailsRequestObj
  )
}
```

![image](https://user-images.githubusercontent.com/30155292/115537414-158b1880-a29b-11eb-9bf7-c5b5e26c149e.png)

I am going to play with it and prepare a PR if succeed.

**Comment by lojzatran** [comment]
Hi @Fifciu, 
we made a release with your change (https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v7.1.3). Thank you for contributing.
