### ISSUE TITLE
Status of > 4.0 releases

### ISSUE THREAD

**Issue by SMillerDev** [commercetools/commercetools-adyen-integration#694]
In GitHub they are marked pre-release but that doesn't seem to be reflected in Docker Hub. Which one is correct?

**Comment by SMillerDev** [comment]
Good to hear, I was already running the latest version but the `pre-release` labels had me slightly worried.

**Comment by davie** [comment]
just checking the status of this - all the releases are still marked as pre-release, are they suitable for use in production?

**Comment by SMillerDev** [comment]
@butenkor any update on when there will be a stable release?

**Comment by ibronsveld** [comment]
We are working closely with Adyen to get to a stable release version. Currently, there is one small (but challenging) issue remaining regarding manual approvals done in the Adyen UI. Once that has been fixed, the new version will be released.
