### ISSUE TITLE
Support custom shipping method use with Klarna payment

### ISSUE THREAD

**Issue by pawelphilipczyk** [commercetools/commercetools-adyen-integration#700]
I've got extension up and running and I'm using Adyen dropin component. Card payments are working fine. 

Now the problem starts with Klarna payments and specifically in combination with custom shipping methods in commerce tools. I've managed to track down the issue based on the error below to `_getShippingMethodDescription` function in `Klarna-make-payment.handler.js`. Seems that it's trying to read shipping method description based on reference object and that is probably working only for regular shipping methods not the custom ones. 

This bug is probably easy to fix but I'm wondering why is it doing that anyway? 
Examples in Adyen documentation for Klarna do not seem to have any of this data in the payloads. 

`"Unexpected error (Payment ID: 92164059-4974-4015-a613-5da27de301e3): {\"name\":\"TypeError\",\"message\":\"Cannot read property 'obj' of undefined\",\"stack\":\"TypeError: Cannot read property 'obj' of undefined\\n    at _getShippingMethodDescription (/var/task/src/paymentHandler/klarna-make-payment.handler.js:128:54)\\n    at _createShippingInfoAdyenLineItem (/var/task/src/paymentHandler/klarna-make-payment.handler.js:121:18)\\n    at createLineItems (/var/task/src/paymentHandler/klarna-make-payment.handler.js:58:20)\\n    at Object.execute (/var/task/src/paymentHandler/klarna-make-payment.handler.js:21:41)\\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\\n    at async Promise.all (index 0)\\n    at async Object.handlePayment (/var/task/src/paymentHandler/payment-handler.js:51:28)\\n    at async Runtime.exports.handler (/var/task/index.js:24:27)\"}",
    "time": "2021-05-20T08:08:42.578Z",`

**Comment by lojzatran** [comment]
Hi @pawelphilipczyk,

The reason shipping method is also included within line items is that from our previous experience with Klarna you have to include shipping costs in the payment too. If not, the final price that the customer pays will be lower. We use this link to add shipping to the payment: https://docs.adyen.com/payment-methods/klarna/web-component#make-a-payment-request

**Comment by lojzatran** [comment]
You're right about the bug. We will check within the team when it can be fixed, but you're welcome to provide a PR for that! 😉

**Comment by pawelphilipczyk** [comment]
@lojzatran Thanks for quick reply, I will try to create PR then. There is however something you could help me out with first. According to commerce tools docs (https://docs.commercetools.com/api/projects/shippingMethods#shippingmethod) `ShippingMethod.description` is optional AND now it's deprecated in favour of `localizedDescription`. 

It seems we could switch to it but at the same time this field is missing in custom shipping method which in turn has only something like `shippingMethodName`. 

So maybe we should use `ShippingMethod.name` in the first place and in case of custom methods `shippingMethodName` field? What do you think?
