### ISSUE TITLE
Klarna 14_024 - Invalid open invoice request

### ISSUE THREAD

**Issue by pawelphilipczyk** [commercetools/commercetools-adyen-integration#702]
I'm testing Klarna payments and I'm getting this error response in my `makePaymentResponse` field:

`"{\"status\":422,\"errorCode\":\"14_024\",\"message\":\"Invalid open invoice request.\",\"errorType\":\"validation\",\"pspReference\":\"881621595656366E\"}"`

Now I know for Klarna payment handler adds `lineItems` from the cart but looks like Klarna is expecting something more to complete the payment. 

The only thing that seems related is this example capture request: https://docs.adyen.com/payment-methods/klarna/api-only#-capture-request

I'm not sure if I'm expected to add those `"openinvoicedata..."` lines myself or it's something completely unrelated. The error doesn't say much more and neither does Adyen error codes list. 

Has anyone encountered this problem or has a solution? Thanks in advance 🙂

**Comment by lojzatran** [comment]
Hi @pawelphilipczyk,

Our extension module adds for you only the line items in klarna. If you need `openinvoicedata`, you have to add them yourself. We did not test `openinvoicedata`, so we don't have any experience with it. I redirected your question to Adyen support and will let you know as soon as I get more info.

**Comment by lojzatran** [comment]
Hi @pawelphilipczyk,

according to Adyen you have to add openinvoice lines according to the docs you linked.

**Comment by pawelphilipczyk** [comment]
I've had a couple of back and forth emails with Adyen support trying to make sure my make payment request object shape is correct and has all needed values. 

Finally I've arrived at this shape below which they confirmed should be valid and correct. 
The problem is that it **still throws the same error** as above in the beginning of an issue. 

I'm now thinking maybe extensions is doing something to my request that makes it invalid? I've only focused on what I'm storing in the custom makePaymentRequest field. 

The personal data in this request is what Klarna provides for test payments. Email and merchantAccount is changed of course and values are calculated all in minor units and the sum of amounts is equal.  

```
{
    "amount": {
        "currency": "NOK",
        "value": "1759800"
    },
    "reference": "e40fa666-a613-4d75-b65d-dabff7e90934",
    "paymentMethod": {
        "type": "klarna"
    },
    "returnUrl": "http://localhost:3000/checkout",
    "merchantAccount": "MyAccountECOM",
    "shopperLocale": "no_NO",
    "countryCode": "NO",
    "shopperEmail": "test@example.com",
    "shopperReference": "489d00a9-ec43-45eb-a49d-c4bc5a928dfb",
    "shopperName": {
        "firstName": "Testperson-no",
        "lastName": "Approved"
    },
    "billingAddress": {
        "city": "Oslo",
        "country": "NO",
        "houseNumberOrName": "56",
        "postalCode": "0563",
        "street": "Sæffleberggate"
    },
    "additionalData": {
        "openinvoicedata.numberOfLines": "1",
        "openinvoicedata.line1.currencyCode": "NOK",
        "openinvoicedata.line1.description": "Isola Loddekoffert - utstyr for å lodde Kobber og Zink",
        "openinvoicedata.line1.itemAmount": "695121",
        "openinvoicedata.line1.numberOfItems": "2",
        "openinvoicedata.line1.itemVatAmount": "184779",
        "openinvoicedata.line1.itemVatPercentage": "2100",
        "openinvoicedata.line1.vatCategory": "High"
    }
}
```

**Comment by lojzatran** [comment]
Hi @pawelphilipczyk, 

The extension does add some more fields to the payment object like `merchantAccount`, `metadata` and `applicationInfo`: https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/src/service/web-component-service.js#L21, but it should not make the request fail. You can check the final request that is sent to Adyen in `interfaceInteractions.fields.request`.

Can you test your request in curl or postman by calling the Adyen API directly?

**Comment by pawelphilipczyk** [comment]
Hi @lojzatran it's been a while but we're back on that topic. 

I'm not sure what changed but this is no longer an issue and the payment flow can be tested. 

What happens now is after redirecting back there are no transactions added to payment object. I'm not sure is expected from Klarna or not. There is no mention of this being different for Klarna in documentation. I will investigate this but probably it would be a separate issue to report.

**Comment by butenkor** [comment]
Transactions with an appropriate status are only added when the integration got an obvious OK or NOT OK from Adyen (either through makePaymentRequest, submitAdditionalData or asynchronous notification). In case you have another issue related to transactions please create a new issue since your original error seems to be resolved now.
