### ISSUE TITLE
PayPal payment request

### ISSUE THREAD

**Issue by manju613** [commercetools/commercetools-adyen-integration#720]
Hi, Trying to test Paypal flow - We have configured paypal in Adyen already.

Below request is failing for make payment request from backend, Please share the valid request to use to test from CT pyment API from Postman

{
  "amountPlanned": {
    "currencyCode": "USD",
    "centAmount": 1000
  },
  "paymentMethodInfo": {
    "paymentInterface": "ctp-adyen-integration"
  },
  "custom": {
    "type": {
      "typeId": "type",
      "key": "ctp-adyen-integration-web-components-payment-type"
    },
    "fields": {
    "cartIdReference":"ec345239-b4d5-4270-9f1f-4a37340d29aa",
      "adyenMerchantAccount": "NirmanECOM",
      "commercetoolsProjectKey": "breville-trial",
      "makePaymentRequest": "{\"amount\":{\"currency\": \"EUR\", \"value\": 1000},\"paymentMethod\": {\"type\": \"paypal\",\"subtype\": \"sdk\"},\"reference\": \"Paypal1\",\"merchantAccount\": \"NirmanECOM\"\"}"
    }
  }
}

**Comment by lojzatran** [comment]
Hi @manju613, can you post the error you received? Thank you.
