### ISSUE TITLE
HowToRun suggests manage_project permissions in commercetools

### ISSUE THREAD

**Issue by davie** [commercetools/commercetools-adyen-integration#770]
Both the How to Run docs suggest giving full manage_project access to commercetools, which seems excessive.
Is there a reason that the template "Payment adaptor client" will not work?
That gives manage_payments, view_orders, and view_payments, which seems more appropriate.

https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/HowToRun.md#commercetools
https://github.com/commercetools/commercetools-adyen-integration/blob/master/notification/docs/HowToRun.md#commercetools

**Comment by lojzatran** [comment]
@davie thank you for your suggestion. The template you suggested do not contain all the accesses we need. In our modules we also ensure that certain resources exists like types and extensions, thus we need to read and create them:  https://github.com/commercetools/commercetools-adyen-integration/blob/559a1982dccf05d5373ecde91be43dba03ac2673/extension/src/config/init/ensure-resources.js#L14.

However, `manage_project` scope is indeed excessive. We will check which scopes are really needed and update the documentation accordingly.

**Comment by davie** [comment]
Thanks for the reply.
Looking through the code it doesn't look like that's called at runtime, but only by the setup-resources task, so I'd expect you

**Comment by wiktor-obrebski** [comment]
for the api extension I use: `manage_payments manage_extensions manage_types`
for the notification service I use `manage_payments manage_types`

both seems to work fine.
