### ISSUE TITLE
amountPlanned error occurs when comparing Number with String

### ISSUE THREAD

**Issue by peniakoff** [commercetools/commercetools-adyen-integration#807]
In `validator-builder.js` is possible to compare Number with String, when value of `JSON.parse(makePaymentRequestString).amount` comes as a String but `paymentObject.amountPlanned.centAmount` is (always?) represents by a Number. In this case we'll get the error "AMOUNT_PLANNED_NOT_SAME".
To be sure we compare values from JSON and object we can convert any String to Number.

Related PR: https://github.com/commercetools/commercetools-adyen-integration/pull/806

**Comment by ahmetoz** [comment]
Thanks again for reporting the issue and contribution 🎉  it is added to the latest release: https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v9.0.3
