### ISSUE TITLE
timestamp is not set on transactions

### ISSUE THREAD

**Issue by davie** [commercetools/commercetools-adyen-integration#809]
Hi,
It looks like the timestamp is not being set on transactions when they're created in commercetools, so the date of the transaction is showing as blank.
It looks like this would be easy to add in "src/handler/notification/notification.handler.js" 

`   action: 'addTransaction',
    transaction: {
      type,
      amount: {
        currencyCode: currency,
        centAmount: amount,
      },
      state,
      interactionId,
    },
`
timestamp is available on the notification as "eventDate":"2021-08-25T15:09:19+02:00".
Would it be possible to set  this, or is there a reason not to?

Thanks,
Davie

**Comment by ahmetoz** [comment]
Hey @davie thanks for reporting the use case, there is no reason to add timestamp on the transactions. 
We added this enhancement into our backlog, we will update you when it's released ? Is this ok for you ?

**Comment by peniakoff** [comment]
Timestamp could be needed e.g. when capture is delayed and we need to check if transaction needs to be extended.

**Comment by butenkor** [comment]
Hi @peniakoff I guess ticket can be closed since it has been addressed here? https://github.com/commercetools/commercetools-adyen-integration/pull/826

**Comment by peniakoff** [comment]
Hi, @butenkor , I agree, this ticket can be closed.
