### ISSUE TITLE
Notification error logging

### ISSUE THREAD

**Issue by wiktor-obrebski** [commercetools/commercetools-adyen-integration#813]
When my notification service got unexpected error as result of handling Adyen request I got following error:
```json
{
  "name": "ctp-adyen-integration-notifications",
  "hostname": "...",
  "pid": ...,
  "level": ...,
  "notification": [
    {
      "eventCode": "AUTHORISATION",
      "eventDate": "2021-09-02T14:36:37+02:00",
      "pspReference": "...",
      "success": "true"
    }
  ],
  "cause": {},
  "msg": "Unexpected exception occurred.",
  "time": "2021-09-02T12:36:37.592Z",
  "v": 0
}
```

What is easy to spot here is that I have almost no info what goes wrong.
The `cause` is `{}`.

https://github.com/commercetools/commercetools-adyen-integration/blob/fdb6c149b8007ef138cff7089e492a822e7fa64a/notification/src/utils/error-utils.js#L23-L26

I believe it's because the `getErrorCause` return entire error object instead of `error.message` or at least `String(error)`.
When parsing the `Error` object is just parsed to `{}`.

Here the error is throwed:
https://github.com/commercetools/commercetools-adyen-integration/blob/master/notification/src/api/notification/notification.controller.js#L34

_The issue here is to improve error handling, not to solve my specific case._

**Comment by ahmetoz** [comment]
Hey @wiktor-obrebski  this is already in our backlog and we are working on it, thanks for reporting the issue to us.

**Comment by wiktor-obrebski** [comment]
Thank you.

**Comment by ahmetoz** [comment]
Thanks again for reporting the issue, it is fixed on the latest release: https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v9.0.3
