### ISSUE TITLE
Notification unit test failing

### ISSUE THREAD

**Issue by milindsingh** [commercetools/commercetools-adyen-integration#818]
Unit test -> `given that ADYEN sends an "AUTHORISATION is successful" notification
      when payment has a pending authorization transaction 
      then notification module should add notification to the interface interaction 
      and should update pending authorization state to the success`

fails with error:
```bash
AssertionError: expected [ Array(4) ] to deeply equal [ Array(3) ]
      + expected - actual

         {
           "action": "setMethodInfoMethod"
           "method": "visa"
         }
      -  {
      -    "action": "setMethodInfoName"
      -    "name": {
      -      "en": "Credit card visa"
      -    }
      -  }
       ]
```

**Comment by ahmetoz** [comment]
Hey @milindsingh The problem might be related to configuration that you are using, maybe try with removing getAdyenPaymentMethodsToNames while you running unit tests ?

**Comment by ahmetoz** [comment]
As there is no update on the issue yet, I'm closing it, we could open it again when the issue happens again.
