### ISSUE TITLE
[Hacktoberfest] Add deployment examples for MS Azure

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-adyen-integration#825]
## Situation
In our [deployment examples folder](https://github.com/commercetools/commercetools-adyen-integration/tree/master/deployment-examples) we provide examples how to deploy for AWS and GCP.

## Problem
Some of our customers want to know how to deploy commercetools-adyen-integration extension and notification modules to MS Azure.

## Resolution
Provide a guide and/or example scripts how to deploy to Azure either as docker container or as a serverless function.

**Comment by milindsingh** [comment]
@lojzatran I would to work on this.

**Comment by lojzatran** [comment]
Hi @milindsingh sure! Just create a PR once you're finished, we will review it for you. Thanks for the help.

**Comment by lojzatran** [comment]
Hi @milindsingh how is the progress going? Are you going to create a PR soon? Thanks 🙏

**Comment by milindsingh** [comment]
Its working fine. Will raise a PR by this week.

**Comment by praveenkumarct** [comment]
https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v9.9.2
Released.
