### ISSUE TITLE
Example of making payment using tokenized card

### ISSUE THREAD

**Issue by gagandeepsinghsohi** [commercetools/commercetools-adyen-integration#83]
Hi 
Can you please confirm if this extension can be used to make a payment using the tokenized card? if yes please share Example of making payment using the tokenized card

**Comment by butenkor** [comment]
Hi @gagandeepsinghsohi Yes, here is how we do it: https://github.com/commercetools/commercetools-adyen-integration/blob/64400b7c10b353129d8d805d4a935f9049430efd/extension/src/paymentHandler/creditCard/credit-card-make-payment.handler.js#L91
