### ISSUE TITLE
Hacktoberfest indicates project not participating caused by typo

### ISSUE THREAD

**Issue by HollowMan6** [commercetools/commercetools-adyen-integration#835]
Hi! 

There is a typo in the label of this repository, it should be `hacktoberfest` instead of `hactoberfest`, and which leads to Hacktoberfest indicates that this project is not participating.

![image](https://user-images.githubusercontent.com/43995067/135605726-33c11c8f-528a-49af-8acc-96401c9b5cb7.png)

Recommend the repo owner to fix this.

Thanks!

**Comment by ahmetoz** [comment]
Oh thanks 👍🏽

**Comment by ahmetoz** [comment]
Fixed :)
