### ISSUE TITLE
Support for storing credit cards

### ISSUE THREAD

**Issue by Fifciu** [commercetools/commercetools-adyen-integration#851]
Hello,
Vue Storefront 2 & Adyen integration is getting more and more popular. Agencies are requesting a new feature - Storing payment methods. Is this integration support this feature?

If Yes - how can I use this feature?
If No - are you going to prepare support for it?

To have better understanding, there is doc about requested feature in Magento2 & Adyen integration: https://docs.adyen.com/plugins/magento-2/stored-payment-methods#billing-agreements

**Comment by butenkor** [comment]
Hi @Fifciu , great to hear that integration is working well for you and your customers. We did not explicitly test it but storing payment methods and credit card data should work out the box if you follow the Adyens' guide here (you just need to extend the payload before you send it to commercetools): https://docs.adyen.com/payment-methods/cards/web-component#recurring-payments

Please let us know if it works for you.

**Comment by Fifciu** [comment]
That's great. Sure, I will around the end of the current month

**Comment by butenkor** [comment]
I will close for now - please let me know if you had any issues so that we can reopen it anytime.

**Comment by Fifciu** [comment]
Ah sorry. Everything went smooth and easy :)
