### ISSUE TITLE
Extension Module redundant with release of adyen-web 5.0.0

### ISSUE THREAD

**Issue by MaxAst** [commercetools/commercetools-adyen-integration#853]
I've been in the process of implementing this integration for a client over the last couple of weeks, while Adyen recently released version 5.0.0 of their [adyen-web](https://www.npmjs.com/package/@adyen/adyen-web) npm package.

The major feature of this release is the ability to [create a payment session](https://docs.adyen.com/online-payments/web-drop-in#create-payment-session), which eliminates the need to make a `/payment` request to Adyen on our server. Consequently, this would make the extension module of this repo redundant, wouldn't it?

The implementation we have followed now is:
1. The frontend makes a request to our server with cart ID
2. Our server fetches the total amount of the cart using its ID and creates a commercetools payment with status `BalanceDue` and the key set to a uuid. It uses the same uuid as a `reference` to make a `/sessions` request to Adyen (along with other relevant payment data)
3. Adyen return a session ID and session data, which we return to our frontend
4. The frontend passes the session data into the mounted Adyen Web Drop-In. Payment methods and forms get rendered accordingly.
5. Shopper finishes payment flow on the frontend and frontend displays payment result.
6. Adyen sends a notification to our webhook lambda. We update the commercetools payment accordingly and create an order from the cart

Are there any issues you see in this approach? And would it make sense to consider to upgrade this integration repo with Adyen's new adyen-web version?

**Comment by butenkor** [comment]
Hi @MaxAst as documentation states the integration is build on top of Adyen web-components (https://docs.adyen.com/online-payments/web-components) only. It means it could work to some extent with Adyen drop-in or any other Adyen integration approaches but we can neither confirm it nor support in case you get into issues.

**Comment by MaxAst** [comment]
Hi @butenkor, this release affects web-components in exactly the same way as web drop-in. See https://docs.adyen.com/online-payments/web-components#create-payment-session and the blue info box at the top of the page announcing the release

**Comment by butenkor** [comment]
We are currently evaluating your request. We will keep you updated.

**Comment by MaxAst** [comment]
Hi @butenkor, anything new on this?

**Comment by ahmetoz** [comment]
Hey @MaxAst thanks for opening the issue, and sorry for the late response: 

> Consequently, this would make the extension module of this repo redundant, wouldn't it?

No, because the extension module also manages updates on commercetools payment object, such as adding transactions , it's handling lots of edge cases, beside that it has additional features like cancellation, refund, manual capture, restore etc. 

> Are there any issues you see in this approach? 

I could not as you are following the official adyen documentation, you could do as you wrote but you need to handle commercetools payment part in your merchant service/frontend.

> And would it make sense to consider upgrading this integration repo with Adyen's new adyen-web version?

Here is an official reply from Adyen on this topic (we will add this info also later to the integration FAQ documentation):

> No migration required for existing merchants. The /sessions release is only an orchestration layer on top of existing functionalities. This means that the complete checkout experience is still available and existing merchants will not have to change anything to their existing workflow. In fact, the 3 step /paymentMethods, /payments, /payments/details is still the way to go for more complex user flows. We will be revisiting this topic in Q2 2022 and will keep you updated on the potential upgrade.

**Comment by ahmetoz** [comment]
I'm closing the issue for now, please feel free to reopen in case of open questions.
