### ISSUE TITLE
amountUpdates is not supported

### ISSUE THREAD

**Issue by peniakoff** [commercetools/commercetools-adyen-integration#856]
It looks like the `amountUpdates` action on the Adyen payment is not supported by this integration, e.g. extending of autorisation described here: https://docs.adyen.com/online-payments/adjust-authorisation#extend-authorisation.

**Comment by butenkor** [comment]
Could you please create a feature request here so that we can evaluate your exact business case scenario? https://support.commercetools.com/

**Comment by milindsingh** [comment]
@peniakoff I also need this feature, have you created the request or shall I create one ?

The requirements are that we capture before shipping, but there are case when warehouse is missing some stock (which is rare), we do recalculation and capture a different amount. Pre-authorization might solve this problem.

**Comment by peniakoff** [comment]
Hi, @milindsingh, I didn't prepare any official solution here, for this repo. I've created my own solution for searching payments in the Commecetools and managing them directly on the Adyen side. I know, there is no "connection" between operations on the Adyen and Commercetools side, but after any succeed change in the Adyen, I'm saving also change on the payment object in the Commercetools.

**Comment by butenkor** [comment]
> we capture before shipping

@milindsingh Maybe you could try not to capture right away but pre-authorise only without auto-capture set in Adyen back-office. This would allow you to capture only the required amount with the help of [manual-capture](https://github.com/commercetools/commercetools-adyen-integration/blob/120c995ccfa1a3dfc901a8d466ab4187e484a764/extension/docs/ManualCapture.md#make-an-api-call-to-capture-a-payment). Also, I think it might not be possible to adjust already captured amount as after capture you only option might be to partially refund which is supported by the integration too. 

The issue from @peniakoff is about expiration prevention of the existing pre-authorisation. If your case is different feel free to create a new issue or support request if you would like to share customer specific details.
