### ISSUE TITLE
ADYEN_INTEGRATION_CONFIG as a process variable has a limit of data

### ISSUE THREAD

**Issue by peniakoff** [commercetools/commercetools-adyen-integration#865]
Process environment variables, e.g. in AWS Lambda, is limited to 4KB [https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html). When extension lambda should manage more than few merchants, that is a problem to provide next configurations.
That could be few scenarious to solve this issue:

1. Use external config json file with provided configuration.
2. Use external services, e.g. AWS Secrets, to get configurations
3. Enable possibility to provide more merchants with the same configuration (because it is available in Adyen), e.g.
```
"adyen": [
    {
      "merchants": [
         "merchant_1_name", "merchant_2_name", "..."
       ],
      "apiKey": "...",
      "apiBaseUrl": "...",
      "legacyApiBaseUrl": "...",
      "secretHmacKey": "...",
      "enableHmacSignature": "..."
    }
]

**Comment by ahmetoz** [comment]
Hey @peniakoff 

Thanks for opening the issue we are evaluating it. The environment variable is most portable solution for configuration, so we followed this practice. I wonder how would you pass a config json to your lambda function, is it part of the function archive or external ?

Beside that 4KB also looks enough to me, what happens when you remove whitespaces from the json ?

**Comment by peniakoff** [comment]
4 KB looks enough but not when you need to provide 7 merchants, every of them contains apiKey, apiBaseUrl, legacyApiBaseUrl and secretHmacKey. And yes, my JSON was minified (size is equal 4.0 KB, unminified is about 4.9 KB).
I was thinking about adidtional `config` file added to the main directory during install process. That could be copied somewhere into the app dir structure or we could provide some path as a process env to the config file instead configuration directly in the process env.

**Comment by ahmetoz** [comment]
I think the environment variable should be the default approach, maybe a external file approach could be used as a fallback mechanism so when the project zipped for AWS lambda it could reach it from there, but I'm not sure how it behaves on the AWS lambda 🤔

**Comment by ahmetoz** [comment]
Hey @peniakoff thanks for the fork and contribution! (I quickly checked and could say, I was also checking some approaches that is easy to use and has extendability), can you create a PR from this fork ?

**Comment by peniakoff** [comment]
PR created: https://github.com/commercetools/commercetools-adyen-integration/pull/869

**Comment by ahmetoz** [comment]
Released with https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v9.3.0 hereby I'm closing the issue.
