### ISSUE TITLE
What happens when request fails or timeouts in extension to adyen api call ?

### ISSUE THREAD

**Issue by milindsingh** [commercetools/commercetools-adyen-integration#878]
I was checking for current flow when http request fails or timeouts in extension to adyen api call as I need to add a retry for this.

I need a retry process for manual capture or refund when api fails.

https://github.com/commercetools/commercetools-adyen-integration/blob/9200bc9bde547bf91384cf12f16a9646a8441eca/extension/src/service/web-component-service.js#L50-L63

**Comment by ahmetoz** [comment]
Hey @milindsingh thanks for opening the issue, I would like to ask for more details, are you experiencing a situation in your checkout flow that Adyen request fails (or timeouts) ?

When an error happens during the process, Adyen will send a notification for this payment and notification module will handle the rest, which could handle the missing responses case. Does it make sense to you ?

**Comment by milindsingh** [comment]
@ahmetoz I only need know the current flow, i.e. what will happen if the `callAdyen` fails with timeout or network failure.
Lets assume I am trying to manually capture the payment by adding a `charge` transaction in CT, but `CT -> Adyen API` fails in `callAdyen`, So the respective CT payment will have what update?

**Comment by ahmetoz** [comment]
Hey @milindsingh 

If Adyen call fails you could find the response on respective ct payment customfields and interface interactions.

Does it helps ?

**Comment by milindsingh** [comment]
Thanks @ahmetoz for referencing the code. After testing this scenario, I have 2 doubts:

1. Why not we set transaction as `Failure` in else of error case as we are already checking and setting `Pending`
https://github.com/commercetools/commercetools-adyen-integration/blob/5b3aa981fedeec870fabd67b407d3ce32ad66cc5/extension/src/paymentHandler/manual-capture.handler.js#L33-L33

2. Why we are not referencing the `transactionId` in the `pU.createAddInterfaceInteractionAction` for current processed transaction for easy identification of failure case.

**Comment by butenkor** [comment]
Hi @milindsingh, it seems that the issue has been addressed with the introduction of the idempotency Keys for charge/refund [here](https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v9.11.0). Let us know if the issue can be closed.
