### ISSUE TITLE
Question: Adding metadata

### ISSUE THREAD

**Issue by BielsasBucket** [commercetools/commercetools-adyen-integration#881]
Hi, not sure this is an issue. More a question.

Is there a way we can attach more metadata to the adyen request using the extension?

Tried looking in documentation but couldn't see anything. Will check again tho.

**Comment by SDSellers** [comment]
We would like the ability to attach additional metadata to help with internal reporting and analytics. 

For Web Payments, we are still defining what metadata we want but we need the ability to add some.

Our project which was for Store Payments (i.e. Adyen's Terminal API) we attached the ctPaymentId, Shop Assistant Name, Order Number, Receipt Number, StoreId. etc - this helps our data and finance team with reporting.

I hope this answers your query and it would be great if this could be done soon.

Many Thanks.

**Comment by ahmetoz** [comment]
Hey @SDSellers thanks for describing the use case, currently we are evaluating to extend metadata object passed through with custom fields, so yes we would add it as part of the integration so you could pass your metadata with extension module/service. 
Does this help ?

**Comment by SDSellers** [comment]
Yes, it does. Thank you.

One more question, roughly when would this new feature for passing metadata be released. Its due to the nature of my current project so we can plan.

**Comment by ahmetoz** [comment]
@BielsasBucket it will be released soon, I'm working on it.

**Comment by BielsasBucket** [comment]
Thanks, I'll close this for now then.
