### ISSUE TITLE
Question: Line Items and Billing Address, can I send them to Adyen with Card payments?

### ISSUE THREAD

**Issue by SDSellers** [commercetools/commercetools-adyen-integration#882]
Hi,

Is it possible to send LineItems when making card payments? Will the extension pass these along to Adyen to help with the risk score.

We currently are not using the CommerceTools baskets (we plan to in future). Currently, we are using CommerceTools payments only, and I am hoping we can just pass these items and use them in the risk score.

In addition, if I pass extra fields in the additional data would they also be passed along?

**Comment by ahmetoz** [comment]
Hi @SDSellers, 

Yes, extension service will pass the payload to Adyen, I guess in your case you could set other fields such as billingAddress and [lineItems](https://docs.adyen.com/api-explorer/#/CheckoutService/v68/post/payments__reqParam_lineItems
) or additionalData with your `makePaymentRequest`, you could check the fields on Adyen /payments endpoint.

Does this helps ?

**Comment by SDSellers** [comment]
Yes, thank you
