### ISSUE TITLE
Question: What is the best metric for Horizontal Scaling?

### ISSUE THREAD

**Issue by BielsasBucket** [commercetools/commercetools-adyen-integration#886]
Hi,

We are working on a project using the integration and just working through the [Best Practices](https://github.com/commercetools/commercetools-adyen-integration/blob/master/docs/BEST_PRACTICES.md#deployment-best-practices) and we see about enabling Horizontal Scaling. 

Can you advise what would be the best metric to scale against? CPU, MEM etc.

Thanks

**Comment by ahmetoz** [comment]
Hey @BielsasBucket 

My advice for the deployment depends on the platform, here on mentioned best practice document we suggested to scale it as if instance (e.g pods, or docker instance) is failing you could get reply from the other instances thus it's better to have multiple instances behind a load balancer. Does it make sense to you ?

For the capacity, I'm not sure as it depends on the load of the services, to be in safe side I would put enough capacity so the pods/services would not have issue regarding to cpu and memory usage. Also I would suggest monitoring the services on live and adjust the capacity.

For k8s:
Maybe you could check this article: https://learnk8s.io/setting-cpu-memory-limits-requests
Also I could recommend using pod disruption(https://kubernetes.io/docs/concepts/workloads/pods/disruptions/).

AFAIK if you are using serverless functions, the cloud platform would handle the scaleability part for you.

I hope this answer helps for your investigation. 
 
Best Regards, Ahmet.

**Comment by BielsasBucket** [comment]
Thanks, that helps.
