### ISSUE TITLE
Can not do action manual capture

### ISSUE THREAD

**Issue by lambaodiep** [commercetools/commercetools-adyen-integration#887]
I created and registered an extension with CommerceTool, and I also configure the ct project key, Adyen merchant, Adyen API for the live system. 
I tried to call the commerce tool to do action manual capture payment but in the Adyen, the payment status does not change anymore. I also have a staging environment, I tested on staging everything is fine but for live system, I got the problem. I also used the Adyen API key to call Adyen API, and the payment status change as well.

Please help us with this problem, it is super urgent.

**Comment by ahmetoz** [comment]
Hey @lambaodiep 

It might be a configuration issue on your live system, did you get any support from Adyen support ?
Also you might check if you get any notification for this payment from Adyen via the notification web hook.

For troubleshooting, could you please check the logs of your deployed services, in case of an issue on integration it should be logged on your deployed services of integration, also you might check the `interfaceInteractions` array on your commercetools payment, which saves the request/response with adyen calls.

**Comment by lambaodiep** [comment]
hi @ahmetoz 

In the log of response of extension, the value of `interfaceInteractions` is empty, I also check notification, I have receive data in notification so far.

In this url https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/HowToRun.md#adyen

How can I get correct data of these field? I open the menu API URLs in Adyen but I don't know how to get these API.

```
"apiBaseUrl": "https://checkout-test.adyen.com/v65",
"legacyApiBaseUrl": "https://pal-test.adyen.com/pal/servlet/Payment/v65"
```
In Adyen has: Checkout API, Classic Payment API, Classic Recurring API, Point of Sale, Checkout SDK, Terminal Cloud API. Which API I have to get and put to the configure of `ADYEN_INTEGRATION_CONFIG`

**Comment by ahmetoz** [comment]
@lambaodiep looks like issue is related to going live as the test and live is different:

Here official checklist from adyen documentation for the going live: https://docs.adyen.com/online-payments/integration-checklist which is mentioned also here in our integration doc: https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/WebComponentsIntegrationGuide.md#test-and-go-live 

Spesific to urls, you might check links on how to run document in detail also this official adyen link too: https://docs.adyen.com/development-resources/live-endpoints

I might suggest [submitting a support request](https://www.adyen.help/hc/en-us/requests/new) to Adyen directly for the required account setup in case you have Adyen account and configuration related issues. 

Best Regards, Ahmet.

**Comment by lambaodiep** [comment]
hi @ahmetoz 
thanks for your help, now I found my problem, the problem came from this validate
```
function _isAdyenPayment(paymentObject) {
  return (
    paymentObject.paymentMethodInfo.paymentInterface === CTP_ADYEN_INTEGRATION
  )
}
```
It always return false because our data does not match with `ctp-adyen-integration`
