### ISSUE TITLE
Update to Checkout API v6.8 payment sessions flow

### ISSUE THREAD

**Issue by exiguus** [commercetools/commercetools-adyen-integration#908]
Currently, we use adyen-web with the payment flow introduced before adyen-web v5.0.0.
![image](https://user-images.githubusercontent.com/1060633/150330900-62b0187a-5155-487c-b5be-ae00d315bd1e.png)

Since adyen-web v5.0.0, adyen over a session based payment flow.
![image](https://user-images.githubusercontent.com/1060633/150330938-9902bd61-b488-44d6-8096-a59aa9c5ad5b.png)

Will commercetools-adyen-integration support this session based payment flow soon?

Best regards

**Comment by butenkor** [comment]
Hi @exiguus, does [this](https://github.com/commercetools/commercetools-adyen-integration/blob/master/docs/FAQ.md#can-we-use-adyen-web-components--v500-with-this-integration-) answer your question?

**Comment by exiguus** [comment]
Hello @butenkor, thank you for the quick answer.
Indeed, [this](https://github.com/commercetools/commercetools-adyen-integration/blob/master/docs/FAQ.md#can-we-use-adyen-web-components--v500-with-this-integration-) answer my question.
Thanks again!

**Comment by lojzatran** [comment]
Hi @exiguus do you have further questions? If not, I will close this issue. Thank you.
