### ISSUE TITLE
Missing `metadata.ctProjectKey` for some transactions.

### ISSUE THREAD

**Issue by wiktor-obrebski** [commercetools/commercetools-adyen-integration#937]
I found that a small percentage of notifications that our integration got from Adyen does not have `metadata.ctProjectKey` field. 
It breaks the process, as the notification module can not correctly handle such notifications.

In the documentation:
https://github.com/commercetools/commercetools-adyen-integration/blob/master/docs/adr/0003-matching-adyen-notification-in-multitenancy.md

Additionally, I contacted Adyen support. They inform me that sometimes when the notification is sent, they do not have access to transaction meta yet. Therefore, they would need to wait for it, even a few minutes.
In our system, every minute is essential, as we provide services to our customer's houses in 10-30 minutes.

Maybe you can propose something to avoid this issue?
We always use dedicated notification service instances per given Adyen environment. Maybe you can add some optional configuration options, e.g. `defaultAdyenProjectKey` that will automatically assume Adyen project if it is not available in the notification?

**Comment by lojzatran** [comment]
Hi @wiktor-obrebski,

Thank you for contacting us about this problem. 

From what I understood, sometimes with the first notifications they don't contain `metadata.ctProjectKey`, but for the same notifications later on you get with `metadata.ctProjectKey`? And when you test locally, everything is working fine or can you reproduce this problem?

**Comment by wiktor-obrebski** [comment]
It's sporadic. For around ~1 thousand transactions per day, it happens 1-2 times.
There is an example log from notification service (with obscured ids etc.):
```
{..., "level":50,"notification":[{"eventCode":"AUTHORISATION","eventDate":"2022-03-16T22:57:01+01:00","pspReference":"...","success":"true"}],"cause":{"message":"Notification can not be processed as \"metadata.ctProjectKey\"  was not found on the notification.","name":"Error","stack":"Error: Notification can not be processed as \"metadata.ctProjectKey\"  was not found on the notification.\n    at getCtpProjectConfig (/app/src/utils/parser.js:9:11)\n    at handleNotification (/app/src/api/notification/notification.controller.js:24:32)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Server.<anonymous> (/app/src/server.js:14:9)"},"msg":"Unexpected exception occurred.","time":"2022-03-16T21:57:02.408Z","v":0}
--
```

A repeated message later probably has the proper `ctProjectKey`, as some of these transactions are handled by our system later. But this creates delay, which sometimes takes too long. 
Our app can give up with the payment, as from CommerceTools perspective, the payment is still not authorized.
The customer can manipulate his cart later, as the cart has not been ordered yet (as payment has not been confirmed).
Then, even if the transaction is authorised correctly after a few minutes, the value can be not enough to pay for the current cart.
Additionally, the customer can be confused as the app already let him know about payment failure.

I feel that such a `default` project key for a single-tenant environment could fix the issue.

**Comment by lojzatran** [comment]
Thank you for clarification. Your suggestion sounds good for your case, but we might need to find a solution that fits also multi-tenant cases. We will check the problem with the team internally and also with Adyen and get back to you with more info within next week.

**Comment by NearlyUnique** [comment]
We have exactly the same issue. In our case our prod env only has a single `metadata.ctProjectKey` so, assuming the HMAC is valid it could just use that.

**Comment by lojzatran** [comment]
Hi everyone,

I have clarified the issue with Adyen and we will add the workaround as suggested by @wiktor-obrebski. The feature should be available in April.

**Comment by lojzatran** [comment]
Hi @wiktor-obrebski

Sorry for the delay. We discussed this topic again in our team and come up with a solution that would also fit the multi-tenant case. We agreed to get the project key from the notification webhook URL in case `metadata.ctProjectKey` is missing. It means that the user has include in the notification URL the project key as part of the path. We want to release this feature sometimes next week. Does the solution sound good to you?

**Comment by wiktor-obrebski** [comment]
sounds reasonable, we can migrate notification url if you provide documentation with details.

**Comment by wiktor-obrebski** [comment]
I see the change has been merged few days ago. Can a release be prepared?

**Comment by lojzatran** [comment]
Hi @wiktor-obrebski we already implemented the feature and tested successfully as self-deployed server and deployment on GCP. However, we need to make sure that it works on AWS before releasing. This will be finished during next week and then we will release it.

If you want, you can prepare the URL for notification module according to the new structure: https://github.com/commercetools/commercetools-adyen-integration/blob/880f9fb7a92bb80b7d84d10a5af4514a6fb286f8/notification/docs/IntegrationGuide.md#fallback-in-case-metadata-is-not-available. When we release the feature next week, it will work for you out of the box.

**Comment by lojzatran** [comment]
Hi @wiktor-obrebski today we finished testing on AWS and made a new release. Please have a look: https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v9.8.0

**Comment by lojzatran** [comment]
Applied fix should handle the issue until Adyen ensures that metadata is always provided in all the notifications (work in progress on Adyen side). Therefore I am closing this issue. If you have further concerns, please do not hesitate to reopen/create new issue.

**Comment by wiktor-obrebski** [comment]
thank you, I will try to check it this week.
