### ISSUE TITLE
Indirect Payment Methods (like PayPal) have incorrect CAPTURE status in notification

### ISSUE THREAD

**Issue by milindsingh** [commercetools/commercetools-adyen-integration#961]
We are getting "success": true for a PayPal Capture Failure.

The notification module only validates `"success": true` marking the **Capture** Transaction state in commercetools as `Success`, making it very difficult to identify and monitor.

As we are integrated with PayPal through Adyen Extension we believe the logic to mark Capture as Success or Failure should be done by Notification module.

Notification:

```json
{
    "NotificationRequestItem": {
        "additionalData": {
            "paypalErrorCode": "10606",
            "paypalErrorDescription": "Transaction rejected, please contact the buyer.",
            "metadata.ctProjectKey": "*****",
            "acquirerErrorCode": "10606",
            "paymentMethodVariant": "paypal",
            "acquirerErrorDescription": "Transaction rejected, please contact the buyer.",
            "hmacSignature": "*****"
        },
        "amount": {
            "currency": "AUD",
            "value": 72400
        },
        "eventCode": "CAPTURE",
        "eventDate": "2022-04-13T07:14:36+02:00",
        "merchantAccountCode": "*****",
        "merchantReference": "190000*****-****-*****",
        "originalReference": "*****",
        "paymentMethod": "paypal",
        "pspReference": "*****",
        "success": "true"
    }
}
```

Adyen Support Response:

> Hi Milind,
>  
> When you send us the capture request, our system directly responds with [capture-received]. This means we've received the capture requests from your end. All the modifications (such as captures, refunds, cancellations) are done asynchronously in our system. Our system was built on purpose in this way as authorisation traffic will not be influenced by modification actions. We will send you a CAPTURE notification with success=true once the capture request is processed.
>
> 
>  
> This means that our system expects that the capture will work if:
>  
> 1. The balance is available.
> 2. The transaction is not expired.
> 3. etc.
>
> 
 >
>For Online captures (which are directly submitted to the payment method) as well as Offline captures (which are processed through a batch process) our system uses the same process. If we receive a capture request, and above requirements are met then we submit the CAPTURE notification with success=true.
>
> 
>We will send CAPTURE with success=false in case that these requirements are not met. You will then need to review the reason for the capture failing, fix this, and resubmit the capture request.
 >
>If there would be a 'TECHNICAL' issue with the bank or in this case Paypal, we will return a CAPTURE_FAILED notification at a later >point. Keep in mind that this technically can happen even a couple of days after the capture is submitted.
> 
>Please let me know if you have any remaining questions.
> 
>Kind regards,
> 
>Jone Azpillaga
>Technical Support Engineer
>Adyen

**Comment by lojzatran** [comment]
Hi @milindsingh thank you for reporting the issue.

> As we are integrated with PayPal through Adyen Extension we believe the logic to mark Capture as Success or Failure should be done by Notification module.

Can you describe how it should be done according to you? The logic to mark Capture as Success or Failure is already done by the Notification module. Do you mean that the Notification module should also check `additionalData` field additionally to the `success` field?

**Comment by butenkor** [comment]
Hi @milindsingh ,

It seem that according to the answer from the support we are doing the right thing by marking the transaction as "Success" since the provided Adyen notification is `"success": "true"`. If `CAPTURE_FAILED` notification is sent by the Adyen, the integration should set the transaction to "Failure", according to the mapping [here](https://github.com/commercetools/commercetools-adyen-integration/blob/72d32634726578e2a6970f1550bb84fc4a456057/notification/resources/adyen-events.json#L63).

Please verify if integration received an Adyen notification with event type `"eventCode": "CAPTURE_FAILED"`. If yes please provide an example so that we can try it out.

**Comment by milindsingh** [comment]
@butenkor Yes, we received the `CAPTURE_FAILED` with all required details, which could be used to update Transaction State.

```json
{
    "NotificationRequestItem": {
        "additionalData": {
            "paypalErrorCode": "10606",
            "paypalErrorDescription": "Transaction rejected, please contact the buyer.",
            "metadata.ctProjectKey": "****",
            "acquirerErrorCode": "10606",
            "paymentMethodVariant": "paypal",
            "acquirerErrorDescription": "Transaction rejected, please contact the buyer.",
            "hmacSignature": "****"
        },
        "amount": {
            "currency": "AUD",
            "value": 72400
        },
        "eventCode": "CAPTURE_FAILED",
        "eventDate": "2022-04-13T07:17:29+02:00",
        "merchantAccountCode": "****",
        "merchantReference": "****",
        "originalReference": "****",
        "paymentMethod": "paypal",
        "pspReference": "****",
        "success": "true"
    }
}
```

**Comment by lojzatran** [comment]
@milindsingh thank you for the notification snippet. After you received this notification, does the Transaction change to `"transactionType": "Charge", "transactionState": "Failure"`?

**Comment by milindsingh** [comment]
I think after `Success` the transaction state does not change to `Failure` from the notification module logic.

As per logs only `interaction` is added: 

`Update payment with key 190000*****-**** with update actions: `
```json
[
    {
        "action": "addInterfaceInteraction",
        "type": {
            "key": "ctp-adyen-integration-interaction-notification",
            "typeId": "type"
        },
        "fields": {
            "createdAt": "2022-04-13T05:31:37.585Z",
            "status": "capture_failed",
            "type": "notification",
            "notification": "{\"NotificationRequestItem\":{\"additionalData\":{\"paypalErrorCode\":\"10606\",\"paypalErrorDescription\":\"Transaction rejected, please contact the buyer.\",\"metadata.ctProjectKey\":\"cos-prod\",\"acquirerErrorCode\":\"10606\",\"paymentMethodVariant\":\"paypal\",\"acquirerErrorDescription\":\"Transaction rejected, please contact the buyer.\",\"hmacSignature\":\"****=\"},\"amount\":{\"currency\":\"AUD\",\"value\":72400},\"eventCode\":\"CAPTURE_FAILED\",\"eventDate\":\"2022-04-13T07:17:29+02:00\",\"merchantAccountCode\":\"****\",\"merchantReference\":\"************\",\"originalReference\":\"*********\",\"paymentMethod\":\"paypal\",\"pspReference\":\"*******\",\"success\":\"true\"}}"
        }
    }
]
```

**Comment by milindsingh** [comment]
Hi @lojzatran @butenkor  

It have been pending for update for 7days, can you suggest the solution for the case ?

Thanks
