### ISSUE TITLE
Is GooglePay supported by this integration?

### ISSUE THREAD

**Issue by BielsasBucket** [commercetools/commercetools-adyen-integration#991]
Hi,

I am trying to implement GooglePay using the Adyen Web Component and the commercetools-adyen-integration. Whatever I currently try I am getting the following error:

`{"status":422,"errorCode":"5_202","message":"Invalid PayWithGoogle Token","errorType":"validation","pspReference":"MTQ83WBBN5PFWR82"}`

Having contacted Adyen and confirmed the GooglePay setup, when [reading about this error code](https://docs.adyen.com/development-resources/error-codes#google-pay-error-codes) it says the solution is _"Solution: Make sure that you are sending in the correct token. Do not escape the stringified JSON send it as it is."_

I edited my "makePaymentRequest" to try an unescape the GooglePayToken and I keep getting errors about my JSON in "makePaymentRequest" been invalid.

Can anyone advise how to resolve this and confirm that GooglePay will work using this integration?

Regards

**Comment by lojzatran** [comment]
Hi @BielsasBucket,

We are supporting Web Components in Adyen and [according to Adyen](https://docs.adyen.com/online-payments/supported-payment-methods) it should work for GooglePay as well. However, we did not test GooglePay specifically in our tests.

Did you show your `makePaymentRequest` to Adyen support? They might be able to help you. To see what request adyen-integration sends to Adyen please check `payment.interfaceInteractions` field and `"type": "makePayment"`. If Adyen support confirms that your request is correct and it should work, please post your `payment.interfaceInteractions` field here so we can also check.

Thank you.

**Comment by BielsasBucket** [comment]
Sorry - updated "makePayment" as it added some extra things that are not been sent. Should be right now.

**Comment by lojzatran** [comment]
Hi @BielsasBucket 

I had a look at what you sent and it is not a stringified JSON. When I try to do `JSON.parse`, it fails. That is basically what we are doing with `makePaymentRequest` (https://github.com/commercetools/commercetools-adyen-integration/blob/a44113334e333aa679de0834ed91ae994e2fae94/extension/src/paymentHandler/make-payment.handler.js#L12).

If your request is correct, it should be enough to stringify that request using `JSON.strigify` and save this string to `makePaymentRequest` field in the payment. If it still doesn't work for you, can you send the original valid Google Pay JSON so we can try to stringify and parse it?

Thank you.

**Comment by BielsasBucket** [comment]
Hi @lojzatran,

How our system works is we have a web checkout (in this example, it is a test checkout) using the Adyen web component. 

We then pass the response from the Adyen web component to a C# .NET API. We use the types defined in the Adyen .NET Api, we have done this approach for the other payment methods we have implemented using this system. Card, Klarna and Apple Pay (still in development).

Using this method, when we put the `GooglePayDetails` (i.e. the GooglePay details we get from Adyen) `JsonConvert.SerializeObject(paymentReq.PaymentMethod)` we get the following (using Text viewer in Visual Studio):

`{"fundingSource":0,"googlePayCardNetwork":"VISA","googlePayToken":"{\"signature\":\"MEQCIAmcZGgMXthVn24+KpMWEvk3ilm5yP1d/YGe91F3CY/bAiAYXr67ai2J2njf8WsEbuhB8pBaLl432Byngfcw7V7kng\\u003d\\u003d\",\"protocolVersion\":\"ECv1\",\"signedMessage\":\"{\\\"encryptedMessage\\\":\\\"Czo2Ahzs3gCNeCa7kY15BUt/UXSaexFMixkBLxxDOJltigRbGF1a5nTEJ6XXDjhmfdiBQSEmtABsVw/v6u7lQZyDUjHKG188q4iAyCVpXLxFr5B+oGiIP4NW04jUPrdXMCeq7rSNUkBN+QhiafQ4Vm7qYfvDfPEdgyirhRCnZ8qQuXUARr6ZMic0YiMTSflHihbTHDxE+lQJ1juEAGifsopqLGufAwTOfkLgGzRP17u01xrAs4uvqdTDwtT1nhzOccQv0HaqXc3gTRo1nvnhoZxOTV2w1ONdNfT/3wju5gnpWYlB0Rj+QP/gZfSOBGZajfy56xwQo+Tet6nrhacdz3mhmDtobw3pRzyrCiBtyR0Cs84+O8YrDGnO3A6pl7ihnlzGFhtJ4CHm6gZPFuNGUJ+prcgmVdzmP3kpchEZBGEhXqwB/Pf/zT2XDFBYmXtwDcwZbqUqjyX6XWdErnbZusPoDr6JX3pxJgaN98tvv9vG9gwTGNddjqR6t1cV5LHCnVVZywIW7DPVY6zf3m1SDRztUL6pvA\\\\u003d\\\\u003d\\\",\\\"ephemeralPublicKey\\\":\\\"BKQImns0AzaoBgiRo7YnpG/8Un065V8Txwx6u1MoESiJSY/x8fHBOYk+LuarWXtIU3OgXuoJrYbilIQ4eAjvvXE\\\\u003d\\\",\\\"tag\\\":\\\"tf39o4jkHs5pY1N9cuXN4RsC5GHBWV6WOnTKge9RdtU\\\\u003d\\\"}\"}","type":"paywithgoogle"}`

When we perform the same `JsonConvert.SerializeObject(paymentReq)` on the Adyen payment request - this is what we send to `makePaymentRequest` (using Text viewer in Visual Studio):

`{"channel":"Web","additionalData":{"allow3DS2":"true"},"amount":{"currency":"GBP","value":1100},"applicationInfo":{"adyenLibrary":{"name":"adyen-dotnet-api-library","version":"8.1.0"}},"billingAddress":{"city":"London","country":"GB","houseNumberOrName":"221 B","postalCode":"NW1 6XE","street":"Baker Street"},"countryCode":"GB","deliveryAddress":{"city":"London","country":"GB","houseNumberOrName":"221 B","postalCode":"NW1 6XE","street":"Baker Street"},"lineItems":[{"amountIncludingTax":1100,"description":"Socks","id":"Item 2","quantity":1}],"merchantAccount":"S0016_FA_Web","metadata":{"orderNumber":"T999991658469908"},"paymentMethod":{"fundingSource":0,"googlePayCardNetwork":"VISA","googlePayToken":"{\"signature\":\"MEQCIAmcZGgMXthVn24+KpMWEvk3ilm5yP1d/YGe91F3CY/bAiAYXr67ai2J2njf8WsEbuhB8pBaLl432Byngfcw7V7kng\\u003d\\u003d\",\"protocolVersion\":\"ECv1\",\"signedMessage\":\"{\\\"encryptedMessage\\\":\\\"Czo2Ahzs3gCNeCa7kY15BUt/UXSaexFMixkBLxxDOJltigRbGF1a5nTEJ6XXDjhmfdiBQSEmtABsVw/v6u7lQZyDUjHKG188q4iAyCVpXLxFr5B+oGiIP4NW04jUPrdXMCeq7rSNUkBN+QhiafQ4Vm7qYfvDfPEdgyirhRCnZ8qQuXUARr6ZMic0YiMTSflHihbTHDxE+lQJ1juEAGifsopqLGufAwTOfkLgGzRP17u01xrAs4uvqdTDwtT1nhzOccQv0HaqXc3gTRo1nvnhoZxOTV2w1ONdNfT/3wju5gnpWYlB0Rj+QP/gZfSOBGZajfy56xwQo+Tet6nrhacdz3mhmDtobw3pRzyrCiBtyR0Cs84+O8YrDGnO3A6pl7ihnlzGFhtJ4CHm6gZPFuNGUJ+prcgmVdzmP3kpchEZBGEhXqwB/Pf/zT2XDFBYmXtwDcwZbqUqjyX6XWdErnbZusPoDr6JX3pxJgaN98tvv9vG9gwTGNddjqR6t1cV5LHCnVVZywIW7DPVY6zf3m1SDRztUL6pvA\\\\u003d\\\\u003d\\\",\\\"ephemeralPublicKey\\\":\\\"BKQImns0AzaoBgiRo7YnpG/8Un065V8Txwx6u1MoESiJSY/x8fHBOYk+LuarWXtIU3OgXuoJrYbilIQ4eAjvvXE\\\\u003d\\\",\\\"tag\\\":\\\"tf39o4jkHs5pY1N9cuXN4RsC5GHBWV6WOnTKge9RdtU\\\\u003d\\\"}\"}","type":"paywithgoogle"},"origin":"https://localhost:3001","reference":"1d65b4c7-8d8c-4eea-978d-657007a280cc","returnUrl":"https://localhost:3001/api/handleShopperRedirect?client=S0016_FA_Web&paymentId=1d65b4c7-8d8c-4eea-978d-657007a280cc","shopperEmail":"jamesbond007@gmail.com","shopperIP":"::1","shopperLocale":"en_GB","shopperName":{"gender":"UNKNOWN","firstName":"James","lastName":"Bond"},"shopperReference":"T999991658469908"}`

**This request is valid JSON - it will parse** - but then the following error message is returned from Adyen:

`{"status":422,"errorCode":"5_202","message":"Invalid PayWithGoogle Token","errorType":"validation","pspReference":"GX6F3RSB5QHG5S82"}`

This is a screenshot of the Payment in commercetools showing the request:

![image](https://user-images.githubusercontent.com/94182057/180376094-ecfe375f-6eed-4158-821b-d0cbe3c9b631.png)

`"{\"channel\":\"Web\",\"additionalData\":{\"allow3DS2\":\"true\"},\"amount\":{\"currency\":\"GBP\",\"value\":1100},\"applicationInfo\":{\"adyenLibrary\":{\"name\":\"adyen-dotnet-api-library\",\"version\":\"8.1.0\"}},\"billingAddress\":{\"city\":\"London\",\"country\":\"GB\",\"houseNumberOrName\":\"221 B\",\"postalCode\":\"NW1 6XE\",\"street\":\"Baker Street\"},\"countryCode\":\"GB\",\"deliveryAddress\":{\"city\":\"London\",\"country\":\"GB\",\"houseNumberOrName\":\"221 B\",\"postalCode\":\"NW1 6XE\",\"street\":\"Baker Street\"},\"lineItems\":[{\"amountIncludingTax\":1100,\"description\":\"Socks\",\"id\":\"Item 2\",\"quantity\":1}],\"merchantAccount\":\"S0016_FA_Web\",\"metadata\":{\"orderNumber\":\"T999991658469908\"},\"paymentMethod\":{\"fundingSource\":0,\"googlePayCardNetwork\":\"VISA\",\"googlePayToken\":\"{\\\"signature\\\":\\\"MEQCIAmcZGgMXthVn24+KpMWEvk3ilm5yP1d/YGe91F3CY/bAiAYXr67ai2J2njf8WsEbuhB8pBaLl432Byngfcw7V7kng\\\=\\\=\\\",\\\"protocolVersion\\\":\\\"ECv1\\\",\\\"signedMessage\\\":\\\"{\\\\\\\"encryptedMessage\\\\\\\":\\\\\\\"Czo2Ahzs3gCNeCa7kY15BUt/UXSaexFMixkBLxxDOJltigRbGF1a5nTEJ6XXDjhmfdiBQSEmtABsVw/v6u7lQZyDUjHKG188q4iAyCVpXLxFr5B+oGiIP4NW04jUPrdXMCeq7rSNUkBN+QhiafQ4Vm7qYfvDfPEdgyirhRCnZ8qQuXUARr6ZMic0YiMTSflHihbTHDxE+lQJ1juEAGifsopqLGufAwTOfkLgGzRP17u01xrAs4uvqdTDwtT1nhzOccQv0HaqXc3gTRo1nvnhoZxOTV2w1ONdNfT/3wju5gnpWYlB0Rj+QP/gZfSOBGZajfy56xwQo+Tet6nrhacdz3mhmDtobw3pRzyrCiBtyR0Cs84+O8YrDGnO3A6pl7ihnlzGFhtJ4CHm6gZPFuNGUJ+prcgmVdzmP3kpchEZBGEhXqwB/Pf/zT2XDFBYmXtwDcwZbqUqjyX6XWdErnbZusPoDr6JX3pxJgaN98tvv9vG9gwTGNddjqR6t1cV5LHCnVVZywIW7DPVY6zf3m1SDRztUL6pvA\\\\\\\=\\\\\\\=\\\\\\\",\\\\\\\"ephemeralPublicKey\\\\\\\":\\\\\\\"BKQImns0AzaoBgiRo7YnpG/8Un065V8Txwx6u1MoESiJSY/x8fHBOYk+LuarWXtIU3OgXuoJrYbilIQ4eAjvvXE\\\\\\\=\\\\\\\",\\\\\\\"tag\\\\\\\":\\\\\\\"tf39o4jkHs5pY1N9cuXN4RsC5GHBWV6WOnTKge9RdtU\\\\\\\=\\\\\\\"}\\\"}\",\"type\":\"paywithgoogle\"},\"origin\":\"https://localhost:3001\",\"reference\":\"1d65b4c7-8d8c-4eea-978d-657007a280cc\",\"returnUrl\":\"https://localhost:3001/api/handleShopperRedirect?client=S0016_FA_Web&paymentId=1d65b4c7-8d8c-4eea-978d-657007a280cc\",\"shopperEmail\":\"jamesbond007@gmail.com\",\"shopperIP\":\"::1\",\"shopperLocale\":\"en_GB\",\"shopperName\":{\"gender\":\"UNKNOWN\",\"firstName\":\"James\",\"lastName\":\"Bond\"},\"shopperReference\":\"T999991658469908\"}"`

As you can see, the **googlePayToken** has added escaping to the original JSON, [I think] it has to be left as it was from the component when sent to Adyen. 

`{"fundingSource":0,"googlePayCardNetwork":"VISA","googlePayToken":"{\"signature\":\"MEQCIAmcZGgMXthVn24+KpMWEvk3ilm5yP1d/YGe91F3CY/bAiAYXr67ai2J2njf8WsEbuhB8pBaLl432Byngfcw7V7kng\\u003d\\u003d\",\"protocolVersion\":\"ECv1\",\"signedMessage\":\"{\\\"encryptedMessage\\\":\\\"Czo2Ahzs3gCNeCa7kY15BUt/UXSaexFMixkBLxxDOJltigRbGF1a5nTEJ6XXDjhmfdiBQSEmtABsVw/v6u7lQZyDUjHKG188q4iAyCVpXLxFr5B+oGiIP4NW04jUPrdXMCeq7rSNUkBN+QhiafQ4Vm7qYfvDfPEdgyirhRCnZ8qQuXUARr6ZMic0YiMTSflHihbTHDxE+lQJ1juEAGifsopqLGufAwTOfkLgGzRP17u01xrAs4uvqdTDwtT1nhzOccQv0HaqXc3gTRo1nvnhoZxOTV2w1ONdNfT/3wju5gnpWYlB0Rj+QP/gZfSOBGZajfy56xwQo+Tet6nrhacdz3mhmDtobw3pRzyrCiBtyR0Cs84+O8YrDGnO3A6pl7ihnlzGFhtJ4CHm6gZPFuNGUJ+prcgmVdzmP3kpchEZBGEhXqwB/Pf/zT2XDFBYmXtwDcwZbqUqjyX6XWdErnbZusPoDr6JX3pxJgaN98tvv9vG9gwTGNddjqR6t1cV5LHCnVVZywIW7DPVY6zf3m1SDRztUL6pvA\\\\u003d\\\\u003d\\\",\\\"ephemeralPublicKey\\\":\\\"BKQImns0AzaoBgiRo7YnpG/8Un065V8Txwx6u1MoESiJSY/x8fHBOYk+LuarWXtIU3OgXuoJrYbilIQ4eAjvvXE\\\\u003d\\\",\\\"tag\\\":\\\"tf39o4jkHs5pY1N9cuXN4RsC5GHBWV6WOnTKge9RdtU\\\\u003d\\\"}\"}","type":"paywithgoogle"}`

I am not sure, how to do this using this integration. Can you advise? Apologies if I have misunderstood your question/request.

**Comment by BielsasBucket** [comment]
Any update on this, please?

**Comment by lojzatran** [comment]
Hi @BielsasBucket 

I did a test with the original request you posted above. I saved it to `makePaymentRequest` like following:

![Screenshot 2022-07-26 at 12 53 03](https://user-images.githubusercontent.com/803826/180989620-627cae68-c28b-4c04-8d86-1ee70ae27454.png)

Adyen-integration parses that string, adds some additional fields to it and sends it to Adyen as the following object (I modified a bit some values):
```
{
  "channel": "Web",
  "additionalData": {
    "allow3DS2": "true"
  },
  "amount": {
    "currency": "EUR",
    "value": 1000
  },
  "applicationInfo": {
    "merchantApplication": {
      "name": "commercetools-adyen-integration-extension",
      "version": "9.9.0"
    },
    "externalPlatform": {
      "name": "commercetools",
      "integrator": "commercetools Professional Services"
    }
  },
  "billingAddress": {
    "city": "London",
    "country": "GB",
    "houseNumberOrName": "221 B",
    "postalCode": "NW1 6XE",
    "street": "Baker Street"
  },
  "countryCode": "GB",
  "deliveryAddress": {
    "city": "London",
    "country": "GB",
    "houseNumberOrName": "221 B",
    "postalCode": "NW1 6XE",
    "street": "Baker Street"
  },
  "lineItems": [
    {
      "amountIncludingTax": 1000,
      "description": "Socks",
      "id": "Item 2",
      "quantity": 1
    }
  ],
  "merchantAccount": "S0016_FA_Web",
  "metadata": {
    "orderNumber": "T999991658469908",
    "ctProjectKey": "adyen-integration-test"
  },
  "paymentMethod": {
    "fundingSource": 0,
    "googlePayCardNetwork": "VISA",
    "googlePayToken": "{\"signature\":\"MEQCIAmcZGgMXthVn24+KpMWEvk3ilm5yP1d/YGe91F3CY/bAiAYXr67ai2J2njf8WsEbuhB8pBaLl432Byngfcw7V7kng\\u003d\\u003d\",\"protocolVersion\":\"ECv1\",\"signedMessage\":\"{\\\"encryptedMessage\\\":\\\"Czo2Ahzs3gCNeCa7kY15BUt/UXSaexFMixkBLxxDOJltigRbGF1a5nTEJ6XXDjhmfdiBQSEmtABsVw/v6u7lQZyDUjHKG188q4iAyCVpXLxFr5B+oGiIP4NW04jUPrdXMCeq7rSNUkBN+QhiafQ4Vm7qYfvDfPEdgyirhRCnZ8qQuXUARr6ZMic0YiMTSflHihbTHDxE+lQJ1juEAGifsopqLGufAwTOfkLgGzRP17u01xrAs4uvqdTDwtT1nhzOccQv0HaqXc3gTRo1nvnhoZxOTV2w1ONdNfT/3wju5gnpWYlB0Rj+QP/gZfSOBGZajfy56xwQo+Tet6nrhacdz3mhmDtobw3pRzyrCiBtyR0Cs84+O8YrDGnO3A6pl7ihnlzGFhtJ4CHm6gZPFuNGUJ+prcgmVdzmP3kpchEZBGEhXqwB/Pf/zT2XDFBYmXtwDcwZbqUqjyX6XWdErnbZusPoDr6JX3pxJgaN98tvv9vG9gwTGNddjqR6t1cV5LHCnVVZywIW7DPVY6zf3m1SDRztUL6pvA\\\\u003d\\\\u003d\\\",\\\"ephemeralPublicKey\\\":\\\"BKQImns0AzaoBgiRo7YnpG/8Un065V8Txwx6u1MoESiJSY/x8fHBOYk+LuarWXtIU3OgXuoJrYbilIQ4eAjvvXE\\\\u003d\\\",\\\"tag\\\":\\\"tf39o4jkHs5pY1N9cuXN4RsC5GHBWV6WOnTKge9RdtU\\\\u003d\\\"}\"}",
    "type": "paywithgoogle"
  },
  "origin": "https://localhost:3001",
  "reference": "1d65b4c7-8d8c-4eea-978d-657007a280cc",
  "returnUrl": "https://localhost:3001/api/handleShopperRedirect?client=S0016_FA_Web&paymentId=1d65b4c7-8d8c-4eea-978d-657007a280cc",
  "shopperEmail": "jamesbond007@gmail.com",
  "shopperIP": "::1",
  "shopperLocale": "en_GB",
  "shopperName": {
    "gender": "UNKNOWN",
    "firstName": "James",
    "lastName": "Bond"
  },
  "shopperReference": "T999991658469908"
}
```

I compare `googlePayToken` that Adyen-integration sends to Adyen and the one from your original JSON request and they are the same. Therefore the error doesn't happen in the integration.

The only difference I could see is that I am using [JavaScript and its method JSON.stringify](https://github.com/commercetools/commercetools-adyen-integration/blob/a44113334e333aa679de0834ed91ae994e2fae94/extension/test/integration/make-payment.handler.spec.js#L136) to create `makePaymentRequest` and you are using C# .NET API. Please check if there is sth done extra in the C# .NET API.

**Comment by BielsasBucket** [comment]
Hi,

The `makePaymentRequest` you were using is generated AFTER I do the Json serialisation in C#. 

Are you telling me that with that `makePaymentRequest` you are creating the request above and sending that to Adyen?

If so, that would imply, the issue is how the Google Pay payment method is configured in Adyen.

**Comment by lojzatran** [comment]
Hi @BielsasBucket

Yes, `makePaymentRequest` above is being sent to Adyen. I used the JSON you posted above and I created a payment with `makePaymentRequest` custom field. This field is then being parsed and send to Adyen as I wrote in my comment.

**Comment by BielsasBucket** [comment]
Thanks, I'll see what Adyen say.

**Comment by BielsasBucket** [comment]
Hi,

I have spoken to Adyen at length and they believe that the GooglePayToken passed by the integration is over escaped.

"Adyen's API is expecting the googlePayToken to be passed **exactly** as received from Google. With the additional escaping ..., it's safe to say that these payloads are not identical."

I did link this conversation in my Adyen support ticket. The `makePaymentRequest` that is recorded in the Payment:

![image](https://user-images.githubusercontent.com/94182057/183016706-8b10ea9b-dba7-47a7-a12a-20991dccd932.png)

Is overly escaped. I do feel I am been sent round in circles, I would ask again for someone to verify this integration will work with GooglePay for Adyen, please.

**Comment by BielsasBucket** [comment]
Hi,

Further update. Spoken more to Adyen who:

>  checked our logging for successful Google Pay transactions completed by other integrations utilizing commercetools' plug-in and wasn't able to locate any instances, which doesn't bode well

If you could provide an email address, I am happy to cc you in the support request I have open with Adyen. So you can read the exchange I have had with them. 

They seem very sure the issue is related to the request from the commercetools integration is the problem.

Thanks

**Comment by BielsasBucket** [comment]
Hello,

I have just found out I am an idiot! This is now working and the extension works perfectly when the user isn't being really stupid!

Thanks,

**Comment by BielsasBucket** [comment]
I can confirm it works. When used properly!
